package com.i9he.m2b.mapper;

import com.i9he.m2b.model.AfterSaleRefund;

public interface AfterSaleRefundMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund
	 * @mbggenerated
	 */
	int insert(AfterSaleRefund record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund
	 * @mbggenerated
	 */
	int insertSelective(AfterSaleRefund record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund
	 * @mbggenerated
	 */
	AfterSaleRefund selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AfterSaleRefund record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AfterSaleRefund record);

	AfterSaleRefund selectByAfterSaleId(Integer afterSaleId);
}