package com.i9he.m2b.mapper;

import java.util.List;

import com.i9he.m2b.model.AfterSaleRecord;

public interface AfterSaleRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record
	 * @mbggenerated
	 */
	int insert(AfterSaleRecord record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record
	 * @mbggenerated
	 */
	int insertSelective(AfterSaleRecord record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record
	 * @mbggenerated
	 */
	AfterSaleRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AfterSaleRecord record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AfterSaleRecord record);

	List<AfterSaleRecord> selectByAfterSaleId(Integer afterSaleId);
}