package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.AfterSale;
import com.i9he.m2b.model.AfterSaleViewModel;
import com.i9he.m2b.model.search.AfterSaleSearchModel;
import com.i9he.m2b.model.AfterSaleExample;

public interface AfterSaleMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	int countByExample(AfterSaleExample example);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	int insert(AfterSale record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	int insertSelective(AfterSale record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	List<AfterSale> selectByExample(AfterSaleExample example);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	AfterSale selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AfterSale record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AfterSale record);

	AfterSale selectMoreByPrimaryKey(Integer id);
	
	List<AfterSale> selectBySearchModel(AfterSaleSearchModel searchModel, RowBounds rowBounds);
	
	int selectCountBySearchModel(AfterSaleSearchModel searchModel);
	
	List<AfterSale> selectByExample(AfterSaleExample example, RowBounds rowBounds);
	
	List<AfterSaleViewModel> getListViewModel();
}