package com.i9he.m2b.mapper;

import org.apache.ibatis.annotations.Param;

import com.i9he.m2b.model.Alipay;

public interface AlipayMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_alipay
	 * @mbggenerated
	 */
	int insert(Alipay record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_alipay
	 * @mbggenerated
	 */
	int insertSelective(Alipay record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_alipay
	 * @mbggenerated
	 */
	Alipay selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_alipay
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Alipay record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_alipay
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Alipay record);

	Alipay selectByOutTradeNo(String outTradeNo);
	
	Alipay selectByTypeOrderID(@Param("type") Byte type, @Param("orderID") String orderID);
}