package com.i9he.m2b.mapper;

import java.util.List;
import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.Authentication;
import com.i9he.m2b.model.search.AuthenticationSearchModel;

public interface AuthenticationMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication
	 * @mbggenerated
	 */
	int insert(Authentication record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication
	 * @mbggenerated
	 */
	int insertSelective(Authentication record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication
	 * @mbggenerated
	 */
	Authentication selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Authentication record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Authentication record);
    /**
     * 返回单个实体
     * @param record
     * @return
     */
	Authentication findByUserId(Authentication record);
	/**
	 * 查询审核集合
	 * @param asm
	 * @param rs
	 * @return
	 */
	List<Authentication> getList(AuthenticationSearchModel asm,RowBounds rs);
	/**
	 * 分页参数
	 * @param asm
	 * @return
	 */
	int  getTotal(AuthenticationSearchModel asm);
}