package com.i9he.m2b.mapper;

import java.util.List;

import com.i9he.m2b.model.Comment;
import com.i9he.m2b.model.CommentViewModel;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment
     *
     * @mbggenerated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment
     *
     * @mbggenerated
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment
     *
     * @mbggenerated
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Comment record);
    
    /***
     * 根据用户id查评论
     * @param id
     * @return
     */
    List<Comment> selectByUser(Comment comment);

    /***
     * 获取评论总数
     * @param userId
     * @return
     */
    public int  selectCount(Comment comment);
    
    /***
     * 查询所有 评论
     * @param id
     * @return
     */
    List<Comment> selectAllComment(Comment comment);
    
    /***
     * 获取所有评论总数
     * @param userId
     * @return
     */
    public int  selectAllCount(Comment comment);

    /***
     * 根据订单id获取评价 
     */
	public Comment selectByOrderId(Integer id);
	
	List<CommentViewModel> getCommentRankData();
}