package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.Concern;
import com.i9he.m2b.model.InterestedModel;
import com.i9he.m2b.model.RemindInfo;
import com.i9he.m2b.model.search.ConcernSearchModel;

public interface ConcernMapper {
    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern
     *
     * @mbggenerated
     */
    int insert(Concern record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern
     *
     * @mbggenerated
     */
    int insertSelective(Concern record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern
     *
     * @mbggenerated
     */
    Concern selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Concern record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Concern record);
    /**
     * 获取关注列表
     * @param csm
     * @param rb
     * @return
     */
    List<Concern> getConcernGoodsList(ConcernSearchModel csm,RowBounds rb);
    /**
     * 获取关注总数
     * @param csm
     * @return
     */
    int getTotal(ConcernSearchModel csm);
    
    List<RemindInfo> getRemindList();
    
    Concern isConcern(Concern concern);
    
    int concernCount(Integer userId);
    
    Concern isRemind(Concern concern);
    
    List<InterestedModel> getInterestedModel();
    
    
}