package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.ExpressfeeTemplate;
import com.i9he.m2b.model.ExpressfeeTemplateEX;
import com.i9he.m2b.model.search.ExpressfeeTemplateSearchModel;

public interface ExpressfeeTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template
	 * @mbggenerated
	 */
	int insert(ExpressfeeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template
	 * @mbggenerated
	 */
	int insertSelective(ExpressfeeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template
	 * @mbggenerated
	 */
	ExpressfeeTemplate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ExpressfeeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ExpressfeeTemplate record);

	/***
	 * 查询所有运费模板
	 * @param searchModel
	 * @return
	 */
	public List<ExpressfeeTemplateEX> selectTemplateListBySearchModel(ExpressfeeTemplateSearchModel searchModel);
	
	/***
	 * 查询运费模板数
	 * @param searchModel
	 * @return
	 */
	public int selectTemplateCountBySearchModel(ExpressfeeTemplateSearchModel searchModel);

	/***
	 * 根据运费模板ID查模板
	 * @param templateId
	 * @return
	 */
	public ExpressfeeTemplateEX selectTemplateById(Integer templateId);

	public int deleteById(Integer templateId);

	public int disableTemplate(Integer templateId);

	public int enableTemplate(Integer templateId);

	public List<ExpressfeeTemplate> selectTemplateBySearchModel(ExpressfeeTemplateSearchModel searchModel, RowBounds rowBounds);

	public int selectCountBySearchModel(ExpressfeeTemplateSearchModel searchModel);

	public List<String> selectAllExpressName();
	
	
}