package com.i9he.m2b.mapper;

import com.i9he.m2b.model.ExpressfeeGoods;
import org.apache.ibatis.annotations.Param;

public interface ExpressfeeGoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_goods
	 * @mbggenerated
	 */
	int insert(ExpressfeeGoods record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_goods
	 * @mbggenerated
	 */
	int insertSelective(ExpressfeeGoods record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_goods
	 * @mbggenerated
	 */
	ExpressfeeGoods selectByPrimaryKey(@Param("goodsId") Integer goodsId,
			@Param("expressfeeTemplateId") Integer expressfeeTemplateId);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_goods
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ExpressfeeGoods record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_goods
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ExpressfeeGoods record);

	public Integer selectExistByGoodsId(Integer goodsId);

	public ExpressfeeGoods selectByGoodsId(Integer goodsId);

	int deleteByGoodsId(Integer goodsId);
}