package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.junit.runners.Parameterized.Parameter;

import com.i9he.m2b.model.ExpressfeeType;
import com.sun.org.glassfish.gmbal.ParameterNames;

public interface ExpressfeeTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type
	 * @mbggenerated
	 */
	int insert(ExpressfeeType record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type
	 * @mbggenerated
	 */
	int insertSelective(ExpressfeeType record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type
	 * @mbggenerated
	 */
	ExpressfeeType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ExpressfeeType record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ExpressfeeType record);

	/***
	 * 根据运费模板id查运费方式
	 * @param id
	 * @return
	 */
	public List<ExpressfeeType> selectTypeListByTemplateId(@Param("templateId")Integer templateId);

	public Integer deleteById(Integer id);
}