package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.HistoryOrder;
import com.i9he.m2b.model.search.GsSearchModel;

public interface HistoryOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order
     *
     * @mbggenerated
     */
    int insert(HistoryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order
     *
     * @mbggenerated
     */
    int insertSelective(HistoryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order
     *
     * @mbggenerated
     */
    HistoryOrder selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HistoryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HistoryOrder record);
    
    List<HistoryOrder>  findOrderListByUserId(Integer userId);
    
    List<HistoryOrder> getAll(GsSearchModel asm,RowBounds rs);
	
	int  getCount(GsSearchModel asm);
}