package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.Invoices;
import com.i9he.m2b.model.search.InvoiceSearchModel;

public interface InvoicesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice
     *
     * @mbggenerated
     */
    int insert(Invoices record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice
     *
     * @mbggenerated
     */
    int insertSelective(Invoices record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice
     *
     * @mbggenerated
     */
    Invoices selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Invoices record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Invoices record);

	public int selectCountBySearchModel(InvoiceSearchModel searchModel);

	public List<Invoices> selectBySearchModel(InvoiceSearchModel searchModel,RowBounds rowBounds);
	
	/***
	 * 确定开具发票
	 * @param invoiceId
	 * @return
	 */
	Integer confirmInvoice(Integer invoiceId);
	
	/**
	 * 根据用户id查看发票记录
	 * @param invoiceSearchModel
	 * @return
	 */
	public List<Invoices> selectByUserId(InvoiceSearchModel invoiceSearchModel);

	Invoices selectByOrderId(Integer orderId);
}