package com.i9he.m2b.mapper;

import org.apache.ibatis.annotations.Param;

import com.i9he.m2b.model.JDPay;

public interface JDPayMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_jdpay
	 * @mbggenerated
	 */
	int insert(JDPay record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_jdpay
	 * @mbggenerated
	 */
	int insertSelective(JDPay record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_jdpay
	 * @mbggenerated
	 */
	JDPay selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_jdpay
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(JDPay record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_jdpay
	 * @mbggenerated
	 */
	int updateByPrimaryKey(JDPay record);

	JDPay selectByVoid(String v_oid);
	
	JDPay selectByTypeOrderID(@Param("type") Byte type, @Param("orderID") String orderID);
}