package com.i9he.m2b.mapper;

import java.util.List;

import com.i9he.m2b.model.Loan;

public interface LoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan
     *
     * @mbggenerated
     */
    int insert(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan
     *
     * @mbggenerated
     */
    int insertSelective(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan
     *
     * @mbggenerated
     */
    Loan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Loan record);
    
    Loan findByOrderId(Integer orderId);
    
    List<Loan> getInfo(Integer userId);
}