package com.i9he.m2b.mapper;

import java.util.List;

import com.i9he.m2b.model.LogisticsDetail;

public interface LogisticsDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_detail
	 * @mbggenerated
	 */
	int insert(LogisticsDetail record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_detail
	 * @mbggenerated
	 */
	int insertSelective(LogisticsDetail record);

	/***
	 * 根据物流编号查询记录条数
	 * @param logisticCode
	 * @return
	 */
	public int selectCountByLogCode(String logisticCode);

	/***
	 * 通过运单号查询物流详情
	 * @param logisticCode 
	 * @return
	 */
	public List<LogisticsDetail> selectLogisticsByCode(String logisticCode);
}