package com.i9he.m2b.mapper;

import com.i9he.m2b.model.LogisticsInfo;
import com.i9he.m2b.model.LogisticsViewModel;

public interface LogisticsInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info
	 * @mbggenerated
	 */
	int insert(LogisticsInfo record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info
	 * @mbggenerated
	 */
	int insertSelective(LogisticsInfo record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info
	 * @mbggenerated
	 */
	LogisticsInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(LogisticsInfo record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(LogisticsInfo record);

	/***
	 * 根据物流编号查物流信息 
	 * @param logisticCode
	 * @return
	 */
	public LogisticsInfo selectByLogCode(String logisticCode);

	/***
	 * 根据物流编号查物流
	 * @param code
	 * @return
	 */
	public LogisticsViewModel selectLogisticByCode(String code);
}