package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.MessageType;

public interface MessageTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype
     *
     * @mbggenerated
     */
    int insert(MessageType record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype
     *
     * @mbggenerated
     */
    int insertSelective(MessageType record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype
     *
     * @mbggenerated
     */
    MessageType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MessageType record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MessageType record);
    /**
     * 消息类型列表
     * @param typeName
     * @return
     */
    List<MessageType> getMessageType(String typeName,RowBounds rb);
    /**
     * 分页参数
     * @param name
     * @return
     */
    int getTotal(String name);
    /**
     * 逻辑删除消息类型
     * @param typeId
     * @return
     */
    int deleteMessageType(Integer typeId);
    
}