package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.Message;
import com.i9he.m2b.model.search.MessageSearchModel;

public interface MessageMapper {
    /**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message
	 * @mbggenerated
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message
	 * @mbggenerated
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message
	 * @mbggenerated
	 */
	Message selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Message record);

	/**
     * 分页查询消息记录
     * @param map
     * @return
     */
    List<Message> getUserMessage(MessageSearchModel mm,RowBounds rowBounds);
    /**
     * 条件查询消息总数,查询分页参数
     * @param map
     * @return
     */
    int getUserTotal(MessageSearchModel mm);
    /**
     * 用户清空消息列表
     * @param userId
     * @return
     */
    int updateIsReceiveByUserId(Message record);
    /**
     * 逻辑删除消息
     * @param messageId
     * @return
     */
    int deleteMessage(Integer messageId);
    /**
     * 后台消息列表
     * @param mm
     * @return
     */
    List<Message> getMessage(MessageSearchModel mm,RowBounds rb);
    
    /**
     * 根据url返回消息实体
     * @param url
     * @return
     */
    Message getMessageByUrl(String url);
    
    int updateIsReadByUser(Integer userId);
    
    int deleteMeg(Integer id);
    
    int messageCount(MessageSearchModel mm);
    
}