package com.i9he.m2b.mapper;

import java.util.List;

import com.i9he.m2b.model.PurchaseRequirementAddition;

public interface PurchaseRequirementAdditionMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition
	 * @mbggenerated
	 */
	int insert(PurchaseRequirementAddition record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition
	 * @mbggenerated
	 */
	int insertSelective(PurchaseRequirementAddition record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition
	 * @mbggenerated
	 */
	PurchaseRequirementAddition selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PurchaseRequirementAddition record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PurchaseRequirementAddition record);

	/**
	 * 新增: By Jimmy 2016-12-02
	 */
	public List<PurchaseRequirementAddition> selectByRequirementId(Integer requirementId);
}