package com.i9he.m2b.mapper;

import java.util.List;

import com.i9he.m2b.model.PurchaseRequirementOffer;

public interface PurchaseRequirementOfferMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer
	 * @mbggenerated
	 */
	int insert(PurchaseRequirementOffer record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer
	 * @mbggenerated
	 */
	int insertSelective(PurchaseRequirementOffer record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer
	 * @mbggenerated
	 */
	PurchaseRequirementOffer selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PurchaseRequirementOffer record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PurchaseRequirementOffer record);

	/**
	 * 新增: By Jimmy
	 */
	public PurchaseRequirementOffer selectByRequirementId(Integer requirementId);
}