package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.PurchaseRequirement;
import com.i9he.m2b.model.search.PurchaseRequirementSearchModel;

public interface PurchaseRequirementMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement
	 * @mbggenerated
	 */
	int insert(PurchaseRequirement record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement
	 * @mbggenerated
	 */
	int insertSelective(PurchaseRequirement record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement
	 * @mbggenerated
	 */
	PurchaseRequirement selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PurchaseRequirement record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PurchaseRequirement record);

	/**
	 * 新增: By Jimmy 2016-12-01
	 */
	List<PurchaseRequirement> selectBySearchModel(PurchaseRequirementSearchModel searchModel, RowBounds rowBounds);
	
	int selectCountBySearchModel(PurchaseRequirementSearchModel searchModel);
}