package com.i9he.m2b.mapper;

import java.util.List;

import com.i9he.m2b.model.Seo;

public interface SeoMapper {
    /**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo
	 * @mbggenerated
	 */
	int insert(Seo record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo
	 * @mbggenerated
	 */
	int insertSelective(Seo record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo
	 * @mbggenerated
	 */
	Seo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Seo record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Seo record);

	int deleteByPrimaryKey(Integer id);
    
    List<Seo> selectAll();
    
    Seo selectByUrl(String url);
}