package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.SerialNumber;
import com.i9he.m2b.model.search.SerialSearchModel;

public interface SerialNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number
     *
     * @mbggenerated
     */
    int insert(SerialNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number
     *
     * @mbggenerated
     */
    int insertSelective(SerialNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number
     *
     * @mbggenerated
     */
    SerialNumber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SerialNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SerialNumber record);
    
    List<SerialNumber> getAll(SerialSearchModel ssm,RowBounds rs);
    
    int getCount(SerialSearchModel ssm);
    
    SerialNumber  getSerialNumberModel(@Param("id")Integer id);
    
}