package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.i9he.m2b.model.Subscribe;

public interface SubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_subscribe
     *
     * @mbggenerated
     */
    int insert(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_subscribe
     *
     * @mbggenerated
     */
    int insertSelective(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_subscribe
     *
     * @mbggenerated
     */
    Subscribe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_subscribe
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_subscribe
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Subscribe record);

	public List<Subscribe> selectByUserId(Integer userId);

	public Integer deleteByTagId(@Param("tagId")Integer tagId, @Param("userId")Integer userId);
}