package com.i9he.m2b.mapper;

import java.util.List;

import com.i9he.m2b.model.TagCategory;

public interface TagCategoryMapper {
    /**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category
	 * @mbggenerated
	 */
	int insert(TagCategory record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category
	 * @mbggenerated
	 */
	int insertSelective(TagCategory record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category
	 * @mbggenerated
	 */
	TagCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TagCategory record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TagCategory record);

	/**
     * 新增 获取所有标签分类
     * @return
     */
    List<TagCategory> selectAll();
    
    /**
     * 删除标签分类
     * @param id
     * @return
     */
    int deleteByPrimaryKey(Integer id);
}