package com.i9he.m2b.mapper;

import java.util.Collection;

import com.i9he.m2b.model.TagCategoryMapping;
import org.apache.ibatis.annotations.Param;

public interface TagCategoryMappingMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_cate_mapping
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(@Param("categoryId") Integer categoryId, @Param("tagId") Integer tagId);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_cate_mapping
	 * @mbggenerated
	 */
	int insert(TagCategoryMapping record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_cate_mapping
	 * @mbggenerated
	 */
	int insertSelective(TagCategoryMapping record);

	/**
	 * 新增批量插入
	 */
	int batchReplaceInto(@Param("categoryId") Integer categoryId, @Param("tags") Collection<Integer> tags);
	
	/**
	 * 新增批量删除(不在列表中的)
	 */
	int batchDeleteNotIn(@Param("categoryId") Integer categoryId, @Param("tags") Collection<Integer> tags);
	
}