package com.i9he.m2b.mapper;

import java.util.Collection;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.TagMapping;
import com.i9he.m2b.model.search.TagMappingSearchModel;

public interface TagMappingMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping
	 * @mbggenerated
	 */
	int insert(TagMapping record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping
	 * @mbggenerated
	 */
	int insertSelective(TagMapping record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping
	 * @mbggenerated
	 */
	TagMapping selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TagMapping record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TagMapping record);

	/**
	 * 新增: By Jimmy 2016-11-30
	 */
	List<TagMapping> selectBySearchModel(TagMappingSearchModel searchModel, RowBounds rowBounds);
	
	int selectCountBySearchModel(TagMappingSearchModel searchModel);
	
	/**
	 * 新增批量插入
	 */
	int batchInsertIgnore(@Param("items") List<TagMapping> items);
	
	/**
	 * 批量删除(not in)
	 * @param tagId
	 * @param idList
	 * @return
	 */
	int batchDelete(@Param("tagId") Integer tagId, @Param("idList") Collection<Integer> idList);
}