package com.i9he.m2b.mapper;

import com.i9he.m2b.model.UserExpand;

public interface UserExpandMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand
	 * @mbggenerated
	 */
	int insert(UserExpand record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand
	 * @mbggenerated
	 */
	int insertSelective(UserExpand record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand
	 * @mbggenerated
	 */
	UserExpand selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserExpand record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserExpand record);
}