package com.i9he.m2b.mapper;

import com.i9he.m2b.model.Wallet;

public interface WalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet
     *
     * @mbggenerated
     */
    int insert(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet
     *
     * @mbggenerated
     */
    int insertSelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet
     *
     * @mbggenerated
     */
    Wallet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Wallet record);
    
    
    Wallet findByUserId(Wallet wallet);
    
    int updateByUserId(Wallet wallet);

	public int updateByUser(Wallet wallet);
	
	public int initPasword();
    
    
}