package com.i9he.m2b.mapper;

import com.i9he.m2b.model.Website;
import com.i9he.m2b.model.WebsiteExample;
import java.util.List;

public interface WebsiteMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_website
	 * @mbggenerated
	 */
	int countByExample(WebsiteExample example);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_website
	 * @mbggenerated
	 */
	int insert(Website record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_website
	 * @mbggenerated
	 */
	int insertSelective(Website record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_website
	 * @mbggenerated
	 */
	List<Website> selectByExampleWithBLOBs(WebsiteExample example);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_website
	 * @mbggenerated
	 */
	List<Website> selectByExample(WebsiteExample example);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_website
	 * @mbggenerated
	 */
	Website selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_website
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Website record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_website
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Website record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_website
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Website record);
	
	// 扩展查询
	List<Website> selectMoreByExample(WebsiteExample example);
}