package com.i9he.m2b.mapper;

import org.apache.ibatis.annotations.Param;

import com.i9he.m2b.model.Wxpay;

public interface WxpayMapper {

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_wxpay
	 * @mbggenerated
	 */
	int insert(Wxpay record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_wxpay
	 * @mbggenerated
	 */
	int insertSelective(Wxpay record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_wxpay
	 * @mbggenerated
	 */
	Wxpay selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_wxpay
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Wxpay record);

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pay_wxpay
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Wxpay record);

	Wxpay selectByOutTradeNo(String outTradeNo);
	
	Wxpay selectByTypeOrderID(@Param("type") Byte type, @Param("orderID") String orderID);
}