package com.i9he.m2b.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.i9he.m2b.model.SyUser;
import com.i9he.m2b.model.ZqUser;
import com.i9he.m2b.model.search.GsSearchModel;
import com.i9he.m2b.model.search.ZqUserSearchModel;

public interface ZqUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_zq_user
     *
     * @mbggenerated
     */
    int insert(ZqUser record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_zq_user
     *
     * @mbggenerated
     */
    int insertSelective(ZqUser record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_zq_user
     *
     * @mbggenerated
     */
    ZqUser selectByPrimaryKey(String userCode);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_zq_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZqUser record);

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_zq_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZqUser record);
    
    List<ZqUser> getAll(ZqUserSearchModel zus,RowBounds rs);
	
	int  getCount(ZqUserSearchModel zus);
}