package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class AfterSaleShipping implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.after_sale_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersaleshipping.afterSaleId.validation.notempty}")
	private Integer afterSaleId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.contact
	 * @mbggenerated
	 */
	@Length(message = "{m2b.aftersaleshipping.contact.validation.length}", max = 50)
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.phone
	 * @mbggenerated
	 */
	@Length(message = "{m2b.aftersaleshipping.phone.validation.length}", max = 50)
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.refund_shipping_id
	 * @mbggenerated
	 */
	private Integer refundShippingId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.confirm_user_id
	 * @mbggenerated
	 */
	private Integer confirmUserId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.confirm_time
	 * @mbggenerated
	 */
	private Date confirmTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.exchange_shipping_id
	 * @mbggenerated
	 */
	private Integer exchangeShippingId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.id
	 * @return  the value of b2b_ord_after_sale_shipping.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.id
	 * @param id  the value for b2b_ord_after_sale_shipping.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.after_sale_id
	 * @return  the value of b2b_ord_after_sale_shipping.after_sale_id
	 * @mbggenerated
	 */
	public Integer getAfterSaleId() {
		return afterSaleId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.after_sale_id
	 * @param afterSaleId  the value for b2b_ord_after_sale_shipping.after_sale_id
	 * @mbggenerated
	 */
	public void setAfterSaleId(Integer afterSaleId) {
		this.afterSaleId = afterSaleId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.contact
	 * @return  the value of b2b_ord_after_sale_shipping.contact
	 * @mbggenerated
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.contact
	 * @param contact  the value for b2b_ord_after_sale_shipping.contact
	 * @mbggenerated
	 */
	public void setContact(String contact) {
		this.contact = contact == null ? null : contact.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.phone
	 * @return  the value of b2b_ord_after_sale_shipping.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.phone
	 * @param phone  the value for b2b_ord_after_sale_shipping.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.refund_shipping_id
	 * @return  the value of b2b_ord_after_sale_shipping.refund_shipping_id
	 * @mbggenerated
	 */
	public Integer getRefundShippingId() {
		return refundShippingId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.refund_shipping_id
	 * @param refundShippingId  the value for b2b_ord_after_sale_shipping.refund_shipping_id
	 * @mbggenerated
	 */
	public void setRefundShippingId(Integer refundShippingId) {
		this.refundShippingId = refundShippingId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.confirm_user_id
	 * @return  the value of b2b_ord_after_sale_shipping.confirm_user_id
	 * @mbggenerated
	 */
	public Integer getConfirmUserId() {
		return confirmUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.confirm_user_id
	 * @param confirmUserId  the value for b2b_ord_after_sale_shipping.confirm_user_id
	 * @mbggenerated
	 */
	public void setConfirmUserId(Integer confirmUserId) {
		this.confirmUserId = confirmUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.confirm_time
	 * @return  the value of b2b_ord_after_sale_shipping.confirm_time
	 * @mbggenerated
	 */
	public Date getConfirmTime() {
		return confirmTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.confirm_time
	 * @param confirmTime  the value for b2b_ord_after_sale_shipping.confirm_time
	 * @mbggenerated
	 */
	public void setConfirmTime(Date confirmTime) {
		this.confirmTime = confirmTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.exchange_shipping_id
	 * @return  the value of b2b_ord_after_sale_shipping.exchange_shipping_id
	 * @mbggenerated
	 */
	public Integer getExchangeShippingId() {
		return exchangeShippingId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_shipping.exchange_shipping_id
	 * @param exchangeShippingId  the value for b2b_ord_after_sale_shipping.exchange_shipping_id
	 * @mbggenerated
	 */
	public void setExchangeShippingId(Integer exchangeShippingId) {
		this.exchangeShippingId = exchangeShippingId;
	}
}