package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class AfterSale implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.id
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.afs_no
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersale.afsNo.validation.notempty}")
	@Length(message = "{m2b.aftersale.afsNo.validation.length}", max = 50)
	private String afsNo;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersale.userId.validation.notempty}")
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.order_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersale.orderId.validation.notempty}")
	private Integer orderId;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.goods_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersale.goodsId.validation.notempty}")
	private Integer goodsId;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.goods_qty
	 * @mbggenerated
	 */
	private Integer goodsQty;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.type
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersale.type.validation.notempty}")
	private Byte type;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.reason
	 * @mbggenerated
	 */
	@Length(message = "{m2b.aftersale.reason.validation.length}", max = 50)
	private String reason;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.description
	 * @mbggenerated
	 */
	@Length(message = "{m2b.aftersale.description.validation.length}", max = 500)
	private String description;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.file
	 * @mbggenerated
	 */
	@Length(message = "{m2b.aftersale.file.validation.length}", max = 255)
	private String file;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersale.createTime.validation.notempty}")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.state
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersale.state.validation.notempty}")
	private Byte state;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_user_id
	 * @mbggenerated
	 */
	private Integer processUserId;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_time
	 * @mbggenerated
	 */
	private Date processTime;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.last_process_user_id
	 * @mbggenerated
	 */
	private Integer lastProcessUserId;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.last_process_time
	 * @mbggenerated
	 */
	private Date lastProcessTime;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_description
	 * @mbggenerated
	 */
	@Length(message = "{m2b.aftersale.processDescription.validation.length}", max = 500)
	private String processDescription;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_remark
	 * @mbggenerated
	 */
	@Length(message = "{m2b.aftersale.processRemark.validation.length}", max = 500)
	private String processRemark;

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.id
	 * @return  the value of b2b_ord_after_sale.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.id
	 * @param id  the value for b2b_ord_after_sale.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.afs_no
	 * @return  the value of b2b_ord_after_sale.afs_no
	 * @mbggenerated
	 */
	public String getAfsNo() {
		return afsNo;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.afs_no
	 * @param afsNo  the value for b2b_ord_after_sale.afs_no
	 * @mbggenerated
	 */
	public void setAfsNo(String afsNo) {
		this.afsNo = afsNo == null ? null : afsNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.user_id
	 * @return  the value of b2b_ord_after_sale.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.user_id
	 * @param userId  the value for b2b_ord_after_sale.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.order_id
	 * @return  the value of b2b_ord_after_sale.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.order_id
	 * @param orderId  the value for b2b_ord_after_sale.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.goods_id
	 * @return  the value of b2b_ord_after_sale.goods_id
	 * @mbggenerated
	 */
	public Integer getGoodsId() {
		return goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.goods_id
	 * @param goodsId  the value for b2b_ord_after_sale.goods_id
	 * @mbggenerated
	 */
	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.goods_qty
	 * @return  the value of b2b_ord_after_sale.goods_qty
	 * @mbggenerated
	 */
	public Integer getGoodsQty() {
		return goodsQty;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.goods_qty
	 * @param goodsQty  the value for b2b_ord_after_sale.goods_qty
	 * @mbggenerated
	 */
	public void setGoodsQty(Integer goodsQty) {
		this.goodsQty = goodsQty;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.type
	 * @return  the value of b2b_ord_after_sale.type
	 * @mbggenerated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.type
	 * @param type  the value for b2b_ord_after_sale.type
	 * @mbggenerated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.reason
	 * @return  the value of b2b_ord_after_sale.reason
	 * @mbggenerated
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.reason
	 * @param reason  the value for b2b_ord_after_sale.reason
	 * @mbggenerated
	 */
	public void setReason(String reason) {
		this.reason = reason == null ? null : reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.description
	 * @return  the value of b2b_ord_after_sale.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.description
	 * @param description  the value for b2b_ord_after_sale.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.file
	 * @return  the value of b2b_ord_after_sale.file
	 * @mbggenerated
	 */
	public String getFile() {
		return file;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.file
	 * @param file  the value for b2b_ord_after_sale.file
	 * @mbggenerated
	 */
	public void setFile(String file) {
		this.file = file == null ? null : file.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.create_time
	 * @return  the value of b2b_ord_after_sale.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.create_time
	 * @param createTime  the value for b2b_ord_after_sale.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.state
	 * @return  the value of b2b_ord_after_sale.state
	 * @mbggenerated
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.state
	 * @param state  the value for b2b_ord_after_sale.state
	 * @mbggenerated
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_user_id
	 * @return  the value of b2b_ord_after_sale.process_user_id
	 * @mbggenerated
	 */
	public Integer getProcessUserId() {
		return processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_user_id
	 * @param processUserId  the value for b2b_ord_after_sale.process_user_id
	 * @mbggenerated
	 */
	public void setProcessUserId(Integer processUserId) {
		this.processUserId = processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_time
	 * @return  the value of b2b_ord_after_sale.process_time
	 * @mbggenerated
	 */
	public Date getProcessTime() {
		return processTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_time
	 * @param processTime  the value for b2b_ord_after_sale.process_time
	 * @mbggenerated
	 */
	public void setProcessTime(Date processTime) {
		this.processTime = processTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.last_process_user_id
	 * @return  the value of b2b_ord_after_sale.last_process_user_id
	 * @mbggenerated
	 */
	public Integer getLastProcessUserId() {
		return lastProcessUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.last_process_user_id
	 * @param lastProcessUserId  the value for b2b_ord_after_sale.last_process_user_id
	 * @mbggenerated
	 */
	public void setLastProcessUserId(Integer lastProcessUserId) {
		this.lastProcessUserId = lastProcessUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.last_process_time
	 * @return  the value of b2b_ord_after_sale.last_process_time
	 * @mbggenerated
	 */
	public Date getLastProcessTime() {
		return lastProcessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.last_process_time
	 * @param lastProcessTime  the value for b2b_ord_after_sale.last_process_time
	 * @mbggenerated
	 */
	public void setLastProcessTime(Date lastProcessTime) {
		this.lastProcessTime = lastProcessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_description
	 * @return  the value of b2b_ord_after_sale.process_description
	 * @mbggenerated
	 */
	public String getProcessDescription() {
		return processDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_description
	 * @param processDescription  the value for b2b_ord_after_sale.process_description
	 * @mbggenerated
	 */
	public void setProcessDescription(String processDescription) {
		this.processDescription = processDescription == null ? null : processDescription.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_remark
	 * @return  the value of b2b_ord_after_sale.process_remark
	 * @mbggenerated
	 */
	public String getProcessRemark() {
		return processRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale.process_remark
	 * @param processRemark  the value for b2b_ord_after_sale.process_remark
	 * @mbggenerated
	 */
	public void setProcessRemark(String processRemark) {
		this.processRemark = processRemark == null ? null : processRemark.trim();
	}

	/**
	 * 新增关联查询数据
	 */
	private AfterSaleRefund refund;
	
	private List<AfterSaleShipping> shippings;
	
	private Goods goods;

	public List<AfterSaleShipping> getShippings() {
		return shippings;
	}

	public void setShippings(List<AfterSaleShipping> shippings) {
		this.shippings = shippings;
	}

	public AfterSaleRefund getRefund() {
		return refund;
	}

	public void setRefund(AfterSaleRefund refund) {
		this.refund = refund;
	}
	
	private BigDecimal amount;
	private String goodsName;
	private String goodsImg;
	private String username;
	
	public BigDecimal getAmount() {
		return amount;
	}
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	
	public String getGoodsName() {
		return goodsName;
	}
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName == null ? null : goodsName.trim();
	}
	
	public String getGoodsImg() {
		return goodsImg;
	}
	public void setGoodsImg(String goodsImg) {
		this.goodsImg = goodsImg == null ? null : goodsImg.trim();
	}
	
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

}