package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class AfterSaleRecord implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.after_sale_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersalerecord.afterSaleId.validation.notempty}")
	private Integer afterSaleId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersalerecord.userId.validation.notempty}")
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.service_user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersalerecord.serviceUserId.validation.notempty}")
	private Integer serviceUserId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersalerecord.createTime.validation.notempty}")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.ip
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersalerecord.ip.validation.notempty}")
	@Length(message = "{m2b.aftersalerecord.ip.validation.length}", max = 255)
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.details
	 * @mbggenerated
	 */
	@Length(message = "{m2b.aftersalerecord.details.validation.length}", max = 255)
	private String details;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.id
	 * @return  the value of b2b_ord_after_sale_record.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.id
	 * @param id  the value for b2b_ord_after_sale_record.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.after_sale_id
	 * @return  the value of b2b_ord_after_sale_record.after_sale_id
	 * @mbggenerated
	 */
	public Integer getAfterSaleId() {
		return afterSaleId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.after_sale_id
	 * @param afterSaleId  the value for b2b_ord_after_sale_record.after_sale_id
	 * @mbggenerated
	 */
	public void setAfterSaleId(Integer afterSaleId) {
		this.afterSaleId = afterSaleId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.user_id
	 * @return  the value of b2b_ord_after_sale_record.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.user_id
	 * @param userId  the value for b2b_ord_after_sale_record.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.service_user_id
	 * @return  the value of b2b_ord_after_sale_record.service_user_id
	 * @mbggenerated
	 */
	public Integer getServiceUserId() {
		return serviceUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.service_user_id
	 * @param serviceUserId  the value for b2b_ord_after_sale_record.service_user_id
	 * @mbggenerated
	 */
	public void setServiceUserId(Integer serviceUserId) {
		this.serviceUserId = serviceUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.create_time
	 * @return  the value of b2b_ord_after_sale_record.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.create_time
	 * @param createTime  the value for b2b_ord_after_sale_record.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.ip
	 * @return  the value of b2b_ord_after_sale_record.ip
	 * @mbggenerated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.ip
	 * @param ip  the value for b2b_ord_after_sale_record.ip
	 * @mbggenerated
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.details
	 * @return  the value of b2b_ord_after_sale_record.details
	 * @mbggenerated
	 */
	public String getDetails() {
		return details;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_record.details
	 * @param details  the value for b2b_ord_after_sale_record.details
	 * @mbggenerated
	 */
	public void setDetails(String details) {
		this.details = details == null ? null : details.trim();
	}
}