package com.i9he.m2b.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AfterSaleExample {
    /**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public AfterSaleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("t.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("t.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("t.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("t.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("t.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("t.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("t.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("t.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("t.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("t.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("t.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("t.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAfsNoIsNull() {
			addCriterion("t.afs_no is null");
			return (Criteria) this;
		}

		public Criteria andAfsNoIsNotNull() {
			addCriterion("t.afs_no is not null");
			return (Criteria) this;
		}

		public Criteria andAfsNoEqualTo(String value) {
			addCriterion("t.afs_no =", value, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoNotEqualTo(String value) {
			addCriterion("t.afs_no <>", value, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoGreaterThan(String value) {
			addCriterion("t.afs_no >", value, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoGreaterThanOrEqualTo(String value) {
			addCriterion("t.afs_no >=", value, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoLessThan(String value) {
			addCriterion("t.afs_no <", value, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoLessThanOrEqualTo(String value) {
			addCriterion("t.afs_no <=", value, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoLike(String value) {
			addCriterion("t.afs_no like", value, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoNotLike(String value) {
			addCriterion("t.afs_no not like", value, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoIn(List<String> values) {
			addCriterion("t.afs_no in", values, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoNotIn(List<String> values) {
			addCriterion("t.afs_no not in", values, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoBetween(String value1, String value2) {
			addCriterion("t.afs_no between", value1, value2, "afsNo");
			return (Criteria) this;
		}

		public Criteria andAfsNoNotBetween(String value1, String value2) {
			addCriterion("t.afs_no not between", value1, value2, "afsNo");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("t.user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("t.user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("t.user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("t.user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("t.user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("t.user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("t.user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("t.user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("t.user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("t.user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("t.user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("t.user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("t.order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("t.order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(Integer value) {
			addCriterion("t.order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(Integer value) {
			addCriterion("t.order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(Integer value) {
			addCriterion("t.order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("t.order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(Integer value) {
			addCriterion("t.order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
			addCriterion("t.order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<Integer> values) {
			addCriterion("t.order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<Integer> values) {
			addCriterion("t.order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(Integer value1, Integer value2) {
			addCriterion("t.order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
			addCriterion("t.order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIsNull() {
			addCriterion("t.goods_id is null");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIsNotNull() {
			addCriterion("t.goods_id is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsIdEqualTo(Integer value) {
			addCriterion("t.goods_id =", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotEqualTo(Integer value) {
			addCriterion("t.goods_id <>", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdGreaterThan(Integer value) {
			addCriterion("t.goods_id >", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("t.goods_id >=", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdLessThan(Integer value) {
			addCriterion("t.goods_id <", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
			addCriterion("t.goods_id <=", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIn(List<Integer> values) {
			addCriterion("t.goods_id in", values, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotIn(List<Integer> values) {
			addCriterion("t.goods_id not in", values, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
			addCriterion("t.goods_id between", value1, value2, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
			addCriterion("t.goods_id not between", value1, value2, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyIsNull() {
			addCriterion("t.goods_qty is null");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyIsNotNull() {
			addCriterion("t.goods_qty is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyEqualTo(Integer value) {
			addCriterion("t.goods_qty =", value, "goodsQty");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyNotEqualTo(Integer value) {
			addCriterion("t.goods_qty <>", value, "goodsQty");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyGreaterThan(Integer value) {
			addCriterion("t.goods_qty >", value, "goodsQty");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyGreaterThanOrEqualTo(Integer value) {
			addCriterion("t.goods_qty >=", value, "goodsQty");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyLessThan(Integer value) {
			addCriterion("t.goods_qty <", value, "goodsQty");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyLessThanOrEqualTo(Integer value) {
			addCriterion("t.goods_qty <=", value, "goodsQty");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyIn(List<Integer> values) {
			addCriterion("t.goods_qty in", values, "goodsQty");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyNotIn(List<Integer> values) {
			addCriterion("t.goods_qty not in", values, "goodsQty");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyBetween(Integer value1, Integer value2) {
			addCriterion("t.goods_qty between", value1, value2, "goodsQty");
			return (Criteria) this;
		}

		public Criteria andGoodsQtyNotBetween(Integer value1, Integer value2) {
			addCriterion("t.goods_qty not between", value1, value2, "goodsQty");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("t.`type` is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("t.`type` is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Byte value) {
			addCriterion("t.`type` =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Byte value) {
			addCriterion("t.`type` <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Byte value) {
			addCriterion("t.`type` >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("t.`type` >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Byte value) {
			addCriterion("t.`type` <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Byte value) {
			addCriterion("t.`type` <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Byte> values) {
			addCriterion("t.`type` in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Byte> values) {
			addCriterion("t.`type` not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Byte value1, Byte value2) {
			addCriterion("t.`type` between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("t.`type` not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andReasonIsNull() {
			addCriterion("t.reason is null");
			return (Criteria) this;
		}

		public Criteria andReasonIsNotNull() {
			addCriterion("t.reason is not null");
			return (Criteria) this;
		}

		public Criteria andReasonEqualTo(String value) {
			addCriterion("t.reason =", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotEqualTo(String value) {
			addCriterion("t.reason <>", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonGreaterThan(String value) {
			addCriterion("t.reason >", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonGreaterThanOrEqualTo(String value) {
			addCriterion("t.reason >=", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLessThan(String value) {
			addCriterion("t.reason <", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLessThanOrEqualTo(String value) {
			addCriterion("t.reason <=", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLike(String value) {
			addCriterion("t.reason like", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotLike(String value) {
			addCriterion("t.reason not like", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonIn(List<String> values) {
			addCriterion("t.reason in", values, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotIn(List<String> values) {
			addCriterion("t.reason not in", values, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonBetween(String value1, String value2) {
			addCriterion("t.reason between", value1, value2, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotBetween(String value1, String value2) {
			addCriterion("t.reason not between", value1, value2, "reason");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("t.description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("t.description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("t.description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("t.description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("t.description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("t.description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("t.description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("t.description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("t.description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("t.description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("t.description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("t.description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("t.description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("t.description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andFileIsNull() {
			addCriterion("t.`file` is null");
			return (Criteria) this;
		}

		public Criteria andFileIsNotNull() {
			addCriterion("t.`file` is not null");
			return (Criteria) this;
		}

		public Criteria andFileEqualTo(String value) {
			addCriterion("t.`file` =", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileNotEqualTo(String value) {
			addCriterion("t.`file` <>", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileGreaterThan(String value) {
			addCriterion("t.`file` >", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileGreaterThanOrEqualTo(String value) {
			addCriterion("t.`file` >=", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileLessThan(String value) {
			addCriterion("t.`file` <", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileLessThanOrEqualTo(String value) {
			addCriterion("t.`file` <=", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileLike(String value) {
			addCriterion("t.`file` like", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileNotLike(String value) {
			addCriterion("t.`file` not like", value, "file");
			return (Criteria) this;
		}

		public Criteria andFileIn(List<String> values) {
			addCriterion("t.`file` in", values, "file");
			return (Criteria) this;
		}

		public Criteria andFileNotIn(List<String> values) {
			addCriterion("t.`file` not in", values, "file");
			return (Criteria) this;
		}

		public Criteria andFileBetween(String value1, String value2) {
			addCriterion("t.`file` between", value1, value2, "file");
			return (Criteria) this;
		}

		public Criteria andFileNotBetween(String value1, String value2) {
			addCriterion("t.`file` not between", value1, value2, "file");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("t.create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("t.create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("t.create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("t.create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("t.create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("t.create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("t.create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("t.create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("t.create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("t.create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("t.create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("t.create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("t.`state` is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("t.`state` is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(Byte value) {
			addCriterion("t.`state` =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(Byte value) {
			addCriterion("t.`state` <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(Byte value) {
			addCriterion("t.`state` >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(Byte value) {
			addCriterion("t.`state` >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(Byte value) {
			addCriterion("t.`state` <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(Byte value) {
			addCriterion("t.`state` <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<Byte> values) {
			addCriterion("t.`state` in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<Byte> values) {
			addCriterion("t.`state` not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(Byte value1, Byte value2) {
			addCriterion("t.`state` between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(Byte value1, Byte value2) {
			addCriterion("t.`state` not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdIsNull() {
			addCriterion("t.process_user_id is null");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdIsNotNull() {
			addCriterion("t.process_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdEqualTo(Integer value) {
			addCriterion("t.process_user_id =", value, "processUserId");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdNotEqualTo(Integer value) {
			addCriterion("t.process_user_id <>", value, "processUserId");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdGreaterThan(Integer value) {
			addCriterion("t.process_user_id >", value, "processUserId");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("t.process_user_id >=", value, "processUserId");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdLessThan(Integer value) {
			addCriterion("t.process_user_id <", value, "processUserId");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("t.process_user_id <=", value, "processUserId");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdIn(List<Integer> values) {
			addCriterion("t.process_user_id in", values, "processUserId");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdNotIn(List<Integer> values) {
			addCriterion("t.process_user_id not in", values, "processUserId");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdBetween(Integer value1, Integer value2) {
			addCriterion("t.process_user_id between", value1, value2, "processUserId");
			return (Criteria) this;
		}

		public Criteria andProcessUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("t.process_user_id not between", value1, value2, "processUserId");
			return (Criteria) this;
		}

		public Criteria andProcessTimeIsNull() {
			addCriterion("t.process_time is null");
			return (Criteria) this;
		}

		public Criteria andProcessTimeIsNotNull() {
			addCriterion("t.process_time is not null");
			return (Criteria) this;
		}

		public Criteria andProcessTimeEqualTo(Date value) {
			addCriterion("t.process_time =", value, "processTime");
			return (Criteria) this;
		}

		public Criteria andProcessTimeNotEqualTo(Date value) {
			addCriterion("t.process_time <>", value, "processTime");
			return (Criteria) this;
		}

		public Criteria andProcessTimeGreaterThan(Date value) {
			addCriterion("t.process_time >", value, "processTime");
			return (Criteria) this;
		}

		public Criteria andProcessTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("t.process_time >=", value, "processTime");
			return (Criteria) this;
		}

		public Criteria andProcessTimeLessThan(Date value) {
			addCriterion("t.process_time <", value, "processTime");
			return (Criteria) this;
		}

		public Criteria andProcessTimeLessThanOrEqualTo(Date value) {
			addCriterion("t.process_time <=", value, "processTime");
			return (Criteria) this;
		}

		public Criteria andProcessTimeIn(List<Date> values) {
			addCriterion("t.process_time in", values, "processTime");
			return (Criteria) this;
		}

		public Criteria andProcessTimeNotIn(List<Date> values) {
			addCriterion("t.process_time not in", values, "processTime");
			return (Criteria) this;
		}

		public Criteria andProcessTimeBetween(Date value1, Date value2) {
			addCriterion("t.process_time between", value1, value2, "processTime");
			return (Criteria) this;
		}

		public Criteria andProcessTimeNotBetween(Date value1, Date value2) {
			addCriterion("t.process_time not between", value1, value2, "processTime");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdIsNull() {
			addCriterion("t.last_process_user_id is null");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdIsNotNull() {
			addCriterion("t.last_process_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdEqualTo(Integer value) {
			addCriterion("t.last_process_user_id =", value, "lastProcessUserId");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdNotEqualTo(Integer value) {
			addCriterion("t.last_process_user_id <>", value, "lastProcessUserId");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdGreaterThan(Integer value) {
			addCriterion("t.last_process_user_id >", value, "lastProcessUserId");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("t.last_process_user_id >=", value, "lastProcessUserId");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdLessThan(Integer value) {
			addCriterion("t.last_process_user_id <", value, "lastProcessUserId");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("t.last_process_user_id <=", value, "lastProcessUserId");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdIn(List<Integer> values) {
			addCriterion("t.last_process_user_id in", values, "lastProcessUserId");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdNotIn(List<Integer> values) {
			addCriterion("t.last_process_user_id not in", values, "lastProcessUserId");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdBetween(Integer value1, Integer value2) {
			addCriterion("t.last_process_user_id between", value1, value2, "lastProcessUserId");
			return (Criteria) this;
		}

		public Criteria andLastProcessUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("t.last_process_user_id not between", value1, value2, "lastProcessUserId");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeIsNull() {
			addCriterion("t.last_process_time is null");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeIsNotNull() {
			addCriterion("t.last_process_time is not null");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeEqualTo(Date value) {
			addCriterion("t.last_process_time =", value, "lastProcessTime");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeNotEqualTo(Date value) {
			addCriterion("t.last_process_time <>", value, "lastProcessTime");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeGreaterThan(Date value) {
			addCriterion("t.last_process_time >", value, "lastProcessTime");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("t.last_process_time >=", value, "lastProcessTime");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeLessThan(Date value) {
			addCriterion("t.last_process_time <", value, "lastProcessTime");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeLessThanOrEqualTo(Date value) {
			addCriterion("t.last_process_time <=", value, "lastProcessTime");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeIn(List<Date> values) {
			addCriterion("t.last_process_time in", values, "lastProcessTime");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeNotIn(List<Date> values) {
			addCriterion("t.last_process_time not in", values, "lastProcessTime");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeBetween(Date value1, Date value2) {
			addCriterion("t.last_process_time between", value1, value2, "lastProcessTime");
			return (Criteria) this;
		}

		public Criteria andLastProcessTimeNotBetween(Date value1, Date value2) {
			addCriterion("t.last_process_time not between", value1, value2, "lastProcessTime");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionIsNull() {
			addCriterion("t.process_description is null");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionIsNotNull() {
			addCriterion("t.process_description is not null");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionEqualTo(String value) {
			addCriterion("t.process_description =", value, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionNotEqualTo(String value) {
			addCriterion("t.process_description <>", value, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionGreaterThan(String value) {
			addCriterion("t.process_description >", value, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("t.process_description >=", value, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionLessThan(String value) {
			addCriterion("t.process_description <", value, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionLessThanOrEqualTo(String value) {
			addCriterion("t.process_description <=", value, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionLike(String value) {
			addCriterion("t.process_description like", value, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionNotLike(String value) {
			addCriterion("t.process_description not like", value, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionIn(List<String> values) {
			addCriterion("t.process_description in", values, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionNotIn(List<String> values) {
			addCriterion("t.process_description not in", values, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionBetween(String value1, String value2) {
			addCriterion("t.process_description between", value1, value2, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessDescriptionNotBetween(String value1, String value2) {
			addCriterion("t.process_description not between", value1, value2, "processDescription");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkIsNull() {
			addCriterion("t.process_remark is null");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkIsNotNull() {
			addCriterion("t.process_remark is not null");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkEqualTo(String value) {
			addCriterion("t.process_remark =", value, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkNotEqualTo(String value) {
			addCriterion("t.process_remark <>", value, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkGreaterThan(String value) {
			addCriterion("t.process_remark >", value, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("t.process_remark >=", value, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkLessThan(String value) {
			addCriterion("t.process_remark <", value, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkLessThanOrEqualTo(String value) {
			addCriterion("t.process_remark <=", value, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkLike(String value) {
			addCriterion("t.process_remark like", value, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkNotLike(String value) {
			addCriterion("t.process_remark not like", value, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkIn(List<String> values) {
			addCriterion("t.process_remark in", values, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkNotIn(List<String> values) {
			addCriterion("t.process_remark not in", values, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkBetween(String value1, String value2) {
			addCriterion("t.process_remark between", value1, value2, "processRemark");
			return (Criteria) this;
		}

		public Criteria andProcessRemarkNotBetween(String value1, String value2) {
			addCriterion("t.process_remark not between", value1, value2, "processRemark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_ord_after_sale
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}