package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;

public class AfterSaleRefund implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.after_sale_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.aftersalerefund.afterSaleId.validation.notempty}")
	private Integer afterSaleId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.refund_money
	 * @mbggenerated
	 */
	private BigDecimal refundMoney;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.confirm_refund_money
	 * @mbggenerated
	 */
	private BigDecimal confirmRefundMoney;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.confirm_refund_time
	 * @mbggenerated
	 */
	private Date confirmRefundTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.confirm_refund_user_id
	 * @mbggenerated
	 */
	private Integer confirmRefundUserId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.id
	 * @return  the value of b2b_ord_after_sale_refund.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.id
	 * @param id  the value for b2b_ord_after_sale_refund.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.after_sale_id
	 * @return  the value of b2b_ord_after_sale_refund.after_sale_id
	 * @mbggenerated
	 */
	public Integer getAfterSaleId() {
		return afterSaleId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.after_sale_id
	 * @param afterSaleId  the value for b2b_ord_after_sale_refund.after_sale_id
	 * @mbggenerated
	 */
	public void setAfterSaleId(Integer afterSaleId) {
		this.afterSaleId = afterSaleId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.refund_money
	 * @return  the value of b2b_ord_after_sale_refund.refund_money
	 * @mbggenerated
	 */
	public BigDecimal getRefundMoney() {
		return refundMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.refund_money
	 * @param refundMoney  the value for b2b_ord_after_sale_refund.refund_money
	 * @mbggenerated
	 */
	public void setRefundMoney(BigDecimal refundMoney) {
		this.refundMoney = refundMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.confirm_refund_money
	 * @return  the value of b2b_ord_after_sale_refund.confirm_refund_money
	 * @mbggenerated
	 */
	public BigDecimal getConfirmRefundMoney() {
		return confirmRefundMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.confirm_refund_money
	 * @param confirmRefundMoney  the value for b2b_ord_after_sale_refund.confirm_refund_money
	 * @mbggenerated
	 */
	public void setConfirmRefundMoney(BigDecimal confirmRefundMoney) {
		this.confirmRefundMoney = confirmRefundMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.confirm_refund_time
	 * @return  the value of b2b_ord_after_sale_refund.confirm_refund_time
	 * @mbggenerated
	 */
	public Date getConfirmRefundTime() {
		return confirmRefundTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.confirm_refund_time
	 * @param confirmRefundTime  the value for b2b_ord_after_sale_refund.confirm_refund_time
	 * @mbggenerated
	 */
	public void setConfirmRefundTime(Date confirmRefundTime) {
		this.confirmRefundTime = confirmRefundTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.confirm_refund_user_id
	 * @return  the value of b2b_ord_after_sale_refund.confirm_refund_user_id
	 * @mbggenerated
	 */
	public Integer getConfirmRefundUserId() {
		return confirmRefundUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_ord_after_sale_refund.confirm_refund_user_id
	 * @param confirmRefundUserId  the value for b2b_ord_after_sale_refund.confirm_refund_user_id
	 * @mbggenerated
	 */
	public void setConfirmRefundUserId(Integer confirmRefundUserId) {
		this.confirmRefundUserId = confirmRefundUserId;
	}
}