package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class Authentication implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.authentication.userId.validation.notempty}")
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.name
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.authentication.name.validation.notempty}")
	@Length(message = "{m2b.authentication.name.validation.length}", max = 100)
	private String name;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.licence_no
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.authentication.licenceNo.validation.notempty}")
	@Length(message = "{m2b.authentication.licenceNo.validation.length}", max = 100)
	private String licenceNo;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.licence_photo
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.authentication.licencePhoto.validation.notempty}")
	@Length(message = "{m2b.authentication.licencePhoto.validation.length}", max = 100)
	private String licencePhoto;
	
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.boss_name
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.authentication.bossName.validation.notempty}")
	@Length(message = "{m2b.authentication.bossName.validation.length}", max = 50)
	private String bossName;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.id_card
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.authentication.idCard.validation.notempty}")
	@Length(message = "{m2b.authentication.idCard.validation.length}", max = 50)
	private String idCard;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.exceed
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.authentication.exceed.validation.notempty}")
	private Date exceed;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.authenticator
	 * @mbggenerated
	 */
	@Length(message = "{m2b.authentication.authenticator.validation.length}", max = 50)
	private String authenticator;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.phone
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.authentication.phone.validation.notempty}")
	@Length(message = "{m2b.authentication.phone.validation.length}", max = 50)
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.authentication.createTime.validation.notempty}")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication
	 * @mbggenerated
	 */
	private String cardPhoto1;
	
	private String cardPhoto2;
	
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.id
	 * @return  the value of b2b_user_authentication.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}
	
	
	public String getCardPhoto1() {
		return cardPhoto1;
	}


	public void setCardPhoto1(String cardPhoto1) {
		this.cardPhoto1 = cardPhoto1;
	}


	public String getCardPhoto2() {
		return cardPhoto2;
	}


	public void setCardPhoto2(String cardPhoto2) {
		this.cardPhoto2 = cardPhoto2;
	}


	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.id
	 * @param id  the value for b2b_user_authentication.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.user_id
	 * @return  the value of b2b_user_authentication.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.user_id
	 * @param userId  the value for b2b_user_authentication.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.name
	 * @return  the value of b2b_user_authentication.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.name
	 * @param name  the value for b2b_user_authentication.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.licence_no
	 * @return  the value of b2b_user_authentication.licence_no
	 * @mbggenerated
	 */
	public String getLicenceNo() {
		return licenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.licence_no
	 * @param licenceNo  the value for b2b_user_authentication.licence_no
	 * @mbggenerated
	 */
	public void setLicenceNo(String licenceNo) {
		this.licenceNo = licenceNo == null ? null : licenceNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.licence_photo
	 * @return  the value of b2b_user_authentication.licence_photo
	 * @mbggenerated
	 */
	public String getLicencePhoto() {
		return licencePhoto;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.licence_photo
	 * @param licencePhoto  the value for b2b_user_authentication.licence_photo
	 * @mbggenerated
	 */
	public void setLicencePhoto(String licencePhoto) {
		this.licencePhoto = licencePhoto == null ? null : licencePhoto.trim();
	}

	

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.boss_name
	 * @return  the value of b2b_user_authentication.boss_name
	 * @mbggenerated
	 */
	public String getBossName() {
		return bossName;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.boss_name
	 * @param bossName  the value for b2b_user_authentication.boss_name
	 * @mbggenerated
	 */
	public void setBossName(String bossName) {
		this.bossName = bossName == null ? null : bossName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.id_card
	 * @return  the value of b2b_user_authentication.id_card
	 * @mbggenerated
	 */
	public String getIdCard() {
		return idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.id_card
	 * @param idCard  the value for b2b_user_authentication.id_card
	 * @mbggenerated
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard == null ? null : idCard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.exceed
	 * @return  the value of b2b_user_authentication.exceed
	 * @mbggenerated
	 */
	public Date getExceed() {
		return exceed;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.exceed
	 * @param exceed  the value for b2b_user_authentication.exceed
	 * @mbggenerated
	 */
	public void setExceed(Date exceed) {
		this.exceed = exceed;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.authenticator
	 * @return  the value of b2b_user_authentication.authenticator
	 * @mbggenerated
	 */
	public String getAuthenticator() {
		return authenticator;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.authenticator
	 * @param authenticator  the value for b2b_user_authentication.authenticator
	 * @mbggenerated
	 */
	public void setAuthenticator(String authenticator) {
		this.authenticator = authenticator == null ? null : authenticator
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.phone
	 * @return  the value of b2b_user_authentication.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.phone
	 * @param phone  the value for b2b_user_authentication.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.status
	 * @return  the value of b2b_user_authentication.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.status
	 * @param status  the value for b2b_user_authentication.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.create_time
	 * @return  the value of b2b_user_authentication.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_authentication.create_time
	 * @param createTime  the value for b2b_user_authentication.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}