package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class Business implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{busi.business.userId.validation.notempty}")
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.merchant_no
	 * @mbggenerated
	 */
	@Length(max = 15, message = "{busi.business.merchantNo.validation.length}")
	private String merchantNo;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.sales_persion
	 * @mbggenerated
	 */
	private Integer salesPersion;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.service_persion
	 * @mbggenerated
	 */
	private Integer servicePersion;
	/**
     * 主IP
     * @mbggenerated
     */
	@NotEmpty(message = "{busi.business.mainIp.validation.notempty}")
    private String mainIp;	
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.type
	 * @mbggenerated
	 */
	@NotEmpty(message = "{busi.business.type.validation.notempty}")
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.if_test
	 * @mbggenerated
	 */
	@NotEmpty(message = "{busi.business.ifTest.validation.notempty}")
	private Byte ifTest;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.state
	 * @mbggenerated
	 */
	@NotEmpty(message = "{busi.business.state.validation.notempty}")
	private Byte state;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_type
	 * @mbggenerated
	 */
	private Byte cancelType;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_reason_type
	 * @mbggenerated
	 */
	private Byte cancelReasonType;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_date
	 * @mbggenerated
	 */
	private Date cancelDate;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cycle
	 * @mbggenerated
	 */
	@NotEmpty(message = "{busi.business.cycle.validation.notempty}")
	private Byte cycle;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.deliver_date
	 * @mbggenerated
	 */
	private Date deliverDate;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.strat_date
	 * @mbggenerated
	 */
	private Date stratDate;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.end_date
	 * @mbggenerated
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.order_amount
	 * @mbggenerated
	 */
	private BigDecimal orderAmount;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.renew_amount
	 * @mbggenerated
	 */
	private BigDecimal renewAmount;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.renew_count
	 * @mbggenerated
	 */
	private Integer renewCount;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.created_date
	 * @mbggenerated
	 */
	@NotEmpty(message = "{busi.business.createdDate.validation.notempty}")
	private Date createdDate;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.updated_date
	 * @mbggenerated
	 */
	private Date updatedDate;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.updated_by
	 * @mbggenerated
	 */
	private Integer updatedBy;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.order_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{busi.business.orderId.validation.notempty}")
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.datacenter_id
	 * @mbggenerated
	 */
	@Length(max = 19, message = "{busi.business.datacenterId.validation.length}")
	private String datacenterId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.goods_id
	 * @mbggenerated
	 */
	private Integer goodsId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.goods_name
	 * @mbggenerated
	 */
	@NotEmpty(message = "{busi.business.goodsName.validation.notempty}")
	@Length(max = 255, message = "{busi.business.goodsName.validation.length}")
	private String goodsName;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	private Integer endUserId;
	
	
	public Integer getEndUserId() {
		return endUserId;
	}

	public void setEndUserId(Integer endUserId) {
		this.endUserId = endUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.id
	 * @return  the value of busi_service.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.id
	 * @param id  the value for busi_service.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.user_id
	 * @return  the value of busi_service.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.user_id
	 * @param userId  the value for busi_service.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.merchant_no
	 * @return  the value of busi_service.merchant_no
	 * @mbggenerated
	 */
	public String getMerchantNo() {
		return merchantNo;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.merchant_no
	 * @param merchantNo  the value for busi_service.merchant_no
	 * @mbggenerated
	 */
	public void setMerchantNo(String merchantNo) {
		this.merchantNo = merchantNo == null ? null : merchantNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.sales_persion
	 * @return  the value of busi_service.sales_persion
	 * @mbggenerated
	 */
	public Integer getSalesPersion() {
		return salesPersion;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.sales_persion
	 * @param salesPersion  the value for busi_service.sales_persion
	 * @mbggenerated
	 */
	public void setSalesPersion(Integer salesPersion) {
		this.salesPersion = salesPersion;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.service_persion
	 * @return  the value of busi_service.service_persion
	 * @mbggenerated
	 */
	public Integer getServicePersion() {
		return servicePersion;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.service_persion
	 * @param servicePersion  the value for busi_service.service_persion
	 * @mbggenerated
	 */
	public void setServicePersion(Integer servicePersion) {
		this.servicePersion = servicePersion;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.type
	 * @return  the value of busi_service.type
	 * @mbggenerated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.type
	 * @param type  the value for busi_service.type
	 * @mbggenerated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.if_test
	 * @return  the value of busi_service.if_test
	 * @mbggenerated
	 */
	public Byte getIfTest() {
		return ifTest;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.if_test
	 * @param ifTest  the value for busi_service.if_test
	 * @mbggenerated
	 */
	public void setIfTest(Byte ifTest) {
		this.ifTest = ifTest;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.state
	 * @return  the value of busi_service.state
	 * @mbggenerated
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.state
	 * @param state  the value for busi_service.state
	 * @mbggenerated
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_type
	 * @return  the value of busi_service.cancel_type
	 * @mbggenerated
	 */
	public Byte getCancelType() {
		return cancelType;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_type
	 * @param cancelType  the value for busi_service.cancel_type
	 * @mbggenerated
	 */
	public void setCancelType(Byte cancelType) {
		this.cancelType = cancelType;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_reason_type
	 * @return  the value of busi_service.cancel_reason_type
	 * @mbggenerated
	 */
	public Byte getCancelReasonType() {
		return cancelReasonType;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_reason_type
	 * @param cancelReasonType  the value for busi_service.cancel_reason_type
	 * @mbggenerated
	 */
	public void setCancelReasonType(Byte cancelReasonType) {
		this.cancelReasonType = cancelReasonType;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_date
	 * @return  the value of busi_service.cancel_date
	 * @mbggenerated
	 */
	public Date getCancelDate() {
		return cancelDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_date
	 * @param cancelDate  the value for busi_service.cancel_date
	 * @mbggenerated
	 */
	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}
	
	public String getMainIp() {
		return mainIp;
	}

	public void setMainIp(String mainIp) {
		this.mainIp = mainIp;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cycle
	 * @return  the value of busi_service.cycle
	 * @mbggenerated
	 */
	public Byte getCycle() {
		return cycle;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cycle
	 * @param cycle  the value for busi_service.cycle
	 * @mbggenerated
	 */
	public void setCycle(Byte cycle) {
		this.cycle = cycle;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.deliver_date
	 * @return  the value of busi_service.deliver_date
	 * @mbggenerated
	 */
	public Date getDeliverDate() {
		return deliverDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.deliver_date
	 * @param deliverDate  the value for busi_service.deliver_date
	 * @mbggenerated
	 */
	public void setDeliverDate(Date deliverDate) {
		this.deliverDate = deliverDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.strat_date
	 * @return  the value of busi_service.strat_date
	 * @mbggenerated
	 */
	public Date getStratDate() {
		return stratDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.strat_date
	 * @param stratDate  the value for busi_service.strat_date
	 * @mbggenerated
	 */
	public void setStratDate(Date stratDate) {
		this.stratDate = stratDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.end_date
	 * @return  the value of busi_service.end_date
	 * @mbggenerated
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.end_date
	 * @param endDate  the value for busi_service.end_date
	 * @mbggenerated
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.order_amount
	 * @return  the value of busi_service.order_amount
	 * @mbggenerated
	 */
	public BigDecimal getOrderAmount() {
		return orderAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.order_amount
	 * @param orderAmount  the value for busi_service.order_amount
	 * @mbggenerated
	 */
	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.renew_amount
	 * @return  the value of busi_service.renew_amount
	 * @mbggenerated
	 */
	public BigDecimal getRenewAmount() {
		return renewAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.renew_amount
	 * @param renewAmount  the value for busi_service.renew_amount
	 * @mbggenerated
	 */
	public void setRenewAmount(BigDecimal renewAmount) {
		this.renewAmount = renewAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.renew_count
	 * @return  the value of busi_service.renew_count
	 * @mbggenerated
	 */
	public Integer getRenewCount() {
		return renewCount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.renew_count
	 * @param renewCount  the value for busi_service.renew_count
	 * @mbggenerated
	 */
	public void setRenewCount(Integer renewCount) {
		this.renewCount = renewCount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.created_date
	 * @return  the value of busi_service.created_date
	 * @mbggenerated
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.created_date
	 * @param createdDate  the value for busi_service.created_date
	 * @mbggenerated
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.updated_date
	 * @return  the value of busi_service.updated_date
	 * @mbggenerated
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.updated_date
	 * @param updatedDate  the value for busi_service.updated_date
	 * @mbggenerated
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.updated_by
	 * @return  the value of busi_service.updated_by
	 * @mbggenerated
	 */
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.updated_by
	 * @param updatedBy  the value for busi_service.updated_by
	 * @mbggenerated
	 */
	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.order_id
	 * @return  the value of busi_service.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.order_id
	 * @param orderId  the value for busi_service.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.datacenter_id
	 * @return  the value of busi_service.datacenter_id
	 * @mbggenerated
	 */
	public String getDatacenterId() {
		return datacenterId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.datacenter_id
	 * @param datacenterId  the value for busi_service.datacenter_id
	 * @mbggenerated
	 */
	public void setDatacenterId(String datacenterId) {
		this.datacenterId = datacenterId == null ? null : datacenterId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.goods_id
	 * @return  the value of busi_service.goods_id
	 * @mbggenerated
	 */
	public Integer getGoodsId() {
		return goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.goods_id
	 * @param goodsId  the value for busi_service.goods_id
	 * @mbggenerated
	 */
	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.goods_name
	 * @return  the value of busi_service.goods_name
	 * @mbggenerated
	 */
	public String getGoodsName() {
		return goodsName;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.goods_name
	 * @param goodsName  the value for busi_service.goods_name
	 * @mbggenerated
	 */
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName == null ? null : goodsName.trim();
	}
	
	
	private String cancelReason;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.client_remark
	 * @mbggenerated
	 */
	private String clientRemark;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service.admin_remark
	 * @mbggenerated
	 */
	private String adminRemark;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com busi_service
	 * @mbggenerated
	 */
	

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_reason
	 * @return  the value of busi_service.cancel_reason
	 * @mbggenerated
	 */
	public String getCancelReason() {
		return cancelReason;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.cancel_reason
	 * @param cancelReason  the value for busi_service.cancel_reason
	 * @mbggenerated
	 */
	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason == null ? null : cancelReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.client_remark
	 * @return  the value of busi_service.client_remark
	 * @mbggenerated
	 */
	public String getClientRemark() {
		return clientRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.client_remark
	 * @param clientRemark  the value for busi_service.client_remark
	 * @mbggenerated
	 */
	public void setClientRemark(String clientRemark) {
		this.clientRemark = clientRemark == null ? null : clientRemark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.admin_remark
	 * @return  the value of busi_service.admin_remark
	 * @mbggenerated
	 */
	public String getAdminRemark() {
		return adminRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com busi_service.admin_remark
	 * @param adminRemark  the value for busi_service.admin_remark
	 * @mbggenerated
	 */
	public void setAdminRemark(String adminRemark) {
		this.adminRemark = adminRemark == null ? null : adminRemark.trim();
	}
	
	
	
}