package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;


public class Comment implements Serializable {
    private Integer id;

    private Integer goodsId;

    private Integer userId;
    
    private Integer orderId;

    private String photo;

    private Integer overallComment;

    private Integer goodsSatisfied;

    private Date commentDate;

    private Date replyDate;

    private String content;

    private String replyContent;
    
    private Integer isDel;
    
    //分页	
  	private int pageNo;
  	
  	private int pageSize;
  	
  	private String goodsImage;
  	
  	private List<String> photos; 
  	
  	private String userName;
  	
  	private String sex;
  	
  	private boolean isReply;
  	
  	//存放所属订单信息
  	private String createdDate;
  	private String amount;
  	private String count;
  	
  	//评价总数
  	private Integer allCount;
  	private Integer positiveCount;//好评
  	private Integer mediumCount;//中评
  	private Integer badCount;//差评
  	private Integer photoCount;//有图评价
  	private String commentDegree;//好评度


	public boolean getIsReply() {
		return isReply;
	}


	public void setIsReply(boolean isReply) {
		this.isReply = isReply;
	}


	public String getSex() {
		return sex;
	}


	public void setSex(String sex) {
		this.sex = sex;
	}


	//设置起始页
  	public int getOffset() {
		if(pageNo == 0){
			this.pageNo = 1;
		}
		return (pageNo - 1) * pageSize;
	}
  	
  	
    public String getGoodsImage() {
		return goodsImage;
	}


	public void setGoodsImage(String goodsImage) {
		this.goodsImage = goodsImage;
	}


	public String getAmount() {
		return amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getIsDel() {
		return isDel;
	}

	public void setIsDel(Integer isDel) {
		this.isDel = isDel;
	}

	public int getPageNo() {
		return pageNo;
	}

	public void setPageNo(int pageNo) {
		this.pageNo = pageNo;
	}

	public int getPageSize() {
		return pageSize;
	}

	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}

	public List<String> getPhotos() {
		return photos;
	}

	public void setPhotos(List<String> photos) {
		this.photos = photos;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getAllCount() {
		return allCount;
	}

	public void setAllCount(Integer allCount) {
		this.allCount = allCount;
	}

	public Integer getPositiveCount() {
		return positiveCount;
	}

	public void setPositiveCount(Integer positiveCount) {
		this.positiveCount = positiveCount;
	}

	public Integer getMediumCount() {
		return mediumCount;
	}

	public void setMediumCount(Integer mediumCount) {
		this.mediumCount = mediumCount;
	}

	public Integer getBadCount() {
		return badCount;
	}

	public void setBadCount(Integer badCount) {
		this.badCount = badCount;
	}

	public Integer getPhotoCount() {
		return photoCount;
	}

	public void setPhotoCount(Integer photoCount) {
		this.photoCount = photoCount;
	}

	public String getCommentDegree() {
		return commentDegree;
	}

	public void setCommentDegree(String commentDegree) {
		this.commentDegree = commentDegree;
	}

	/**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.id
     *
     * @return the value of b2b_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.id
     *
     * @param id the value for b2b_comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.goods_id
     *
     * @return the value of b2b_comment.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.goods_id
     *
     * @param goodsId the value for b2b_comment.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.user_id
     *
     * @return the value of b2b_comment.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.user_id
     *
     * @param userId the value for b2b_comment.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.photo
     *
     * @return the value of b2b_comment.photo
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.photo
     *
     * @param photo the value for b2b_comment.photo
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.overall_comment
     *
     * @return the value of b2b_comment.overall_comment
     *
     * @mbggenerated
     */
    public Integer getOverallComment() {
        return overallComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.overall_comment
     *
     * @param overallComment the value for b2b_comment.overall_comment
     *
     * @mbggenerated
     */
    public void setOverallComment(Integer overallComment) {
        this.overallComment = overallComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.goods_satisfied
     *
     * @return the value of b2b_comment.goods_satisfied
     *
     * @mbggenerated
     */
    public Integer getGoodsSatisfied() {
        return goodsSatisfied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.goods_satisfied
     *
     * @param goodsSatisfied the value for b2b_comment.goods_satisfied
     *
     * @mbggenerated
     */
    public void setGoodsSatisfied(Integer goodsSatisfied) {
        this.goodsSatisfied = goodsSatisfied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.comment_date
     *
     * @return the value of b2b_comment.comment_date
     *
     * @mbggenerated
     */
    public Date getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.comment_date
     *
     * @param commentDate the value for b2b_comment.comment_date
     *
     * @mbggenerated
     */
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.reply_date
     *
     * @return the value of b2b_comment.reply_date
     *
     * @mbggenerated
     */
    public Date getReplyDate() {
        return replyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.reply_date
     *
     * @param replyDate the value for b2b_comment.reply_date
     *
     * @mbggenerated
     */
    public void setReplyDate(Date replyDate) {
        this.replyDate = replyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.content
     *
     * @return the value of b2b_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.content
     *
     * @param content the value for b2b_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.reply_content
     *
     * @return the value of b2b_comment.reply_content
     *
     * @mbggenerated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_comment.reply_content
     *
     * @param replyContent the value for b2b_comment.reply_content
     *
     * @mbggenerated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }
}