package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;

public class Concern implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.user_id
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.concern.userId.validation.notempty}")
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.status
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.concern.status.validation.notempty}")
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.price
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.concern.price.validation.notempty}")
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.remind_status
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.concern.remindStatus.validation.notempty}")
    private Byte remindStatus;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.expect_ price
     *
     * @mbggenerated
     */
    private BigDecimal expectPrice;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.create_time
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.concern.createTime.validation.notempty}")
    private Date createTime;
    
    private Integer goodsId;
    
    private Goods goods;
    
	public Integer getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	/**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.id
     *
     * @return the value of b2b_concern.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.id
     *
     * @param id the value for b2b_concern.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.user_id
     *
     * @return the value of b2b_concern.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.user_id
     *
     * @param userId the value for b2b_concern.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.status
     *
     * @return the value of b2b_concern.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.status
     *
     * @param status the value for b2b_concern.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.price
     *
     * @return the value of b2b_concern.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.price
     *
     * @param price the value for b2b_concern.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.remind_status
     *
     * @return the value of b2b_concern.remind_status
     *
     * @mbggenerated
     */
    public Byte getRemindStatus() {
        return remindStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.remind_status
     *
     * @param remindStatus the value for b2b_concern.remind_status
     *
     * @mbggenerated
     */
    public void setRemindStatus(Byte remindStatus) {
        this.remindStatus = remindStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.expect_ price
     *
     * @return the value of b2b_concern.expect_ price
     *
     * @mbggenerated
     */
    public BigDecimal getExpectPrice() {
        return expectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.expect_ price
     *
     * @param expectPrice the value for b2b_concern.expect_ price
     *
     * @mbggenerated
     */
    public void setExpectPrice(BigDecimal expectPrice) {
        this.expectPrice = expectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.create_time
     *
     * @return the value of b2b_concern.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_concern.create_time
     *
     * @param createTime the value for b2b_concern.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}