package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class Contract implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.contract_num
	 * @mbggenerated
	 */
	@Length(message = "{m2b.contract.contractNum.validation.length}", max = 50)
	private String contractNum;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.contract.userId.validation.notempty}")
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.b2b_state
	 * @mbggenerated
	 */
	private Integer b2bState;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.user_state
	 * @mbggenerated
	 */
	private Integer userState;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.b2b_time
	 * @mbggenerated
	 */
	private Date b2bTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.user_time
	 * @mbggenerated
	 */
	private Date userTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.contract_status
	 * @mbggenerated
	 */
	private Integer contractStatus;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.contract_type
	 * @mbggenerated
	 */
	private Integer contractType;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.contract_num
	 * @return  the value of b2b_contract.contract_num
	 * @mbggenerated
	 */
	public String getContractNum() {
		return contractNum;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.contract_num
	 * @param contractNum  the value for b2b_contract.contract_num
	 * @mbggenerated
	 */
	public void setContractNum(String contractNum) {
		this.contractNum = contractNum == null ? null : contractNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.user_id
	 * @return  the value of b2b_contract.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.user_id
	 * @param userId  the value for b2b_contract.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.b2b_state
	 * @return  the value of b2b_contract.b2b_state
	 * @mbggenerated
	 */
	public Integer getB2bState() {
		return b2bState;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.b2b_state
	 * @param b2bState  the value for b2b_contract.b2b_state
	 * @mbggenerated
	 */
	public void setB2bState(Integer b2bState) {
		this.b2bState = b2bState;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.user_state
	 * @return  the value of b2b_contract.user_state
	 * @mbggenerated
	 */
	public Integer getUserState() {
		return userState;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.user_state
	 * @param userState  the value for b2b_contract.user_state
	 * @mbggenerated
	 */
	public void setUserState(Integer userState) {
		this.userState = userState;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.b2b_time
	 * @return  the value of b2b_contract.b2b_time
	 * @mbggenerated
	 */
	public Date getB2bTime() {
		return b2bTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.b2b_time
	 * @param b2bTime  the value for b2b_contract.b2b_time
	 * @mbggenerated
	 */
	public void setB2bTime(Date b2bTime) {
		this.b2bTime = b2bTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.user_time
	 * @return  the value of b2b_contract.user_time
	 * @mbggenerated
	 */
	public Date getUserTime() {
		return userTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.user_time
	 * @param userTime  the value for b2b_contract.user_time
	 * @mbggenerated
	 */
	public void setUserTime(Date userTime) {
		this.userTime = userTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.contract_status
	 * @return  the value of b2b_contract.contract_status
	 * @mbggenerated
	 */
	public Integer getContractStatus() {
		return contractStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.contract_status
	 * @param contractStatus  the value for b2b_contract.contract_status
	 * @mbggenerated
	 */
	public void setContractStatus(Integer contractStatus) {
		this.contractStatus = contractStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.contract_type
	 * @return  the value of b2b_contract.contract_type
	 * @mbggenerated
	 */
	public Integer getContractType() {
		return contractType;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_contract.contract_type
	 * @param contractType  the value for b2b_contract.contract_type
	 * @mbggenerated
	 */
	public void setContractType(Integer contractType) {
		this.contractType = contractType;
	}

	@Override
	public String toString() {
		return "Contract [contractNum=" + contractNum + ", userId=" + userId + ", b2bState=" + b2bState + ", userState=" + userState + ", b2bTime=" + b2bTime + ", userTime=" + userTime
				+ ", contractStatus=" + contractStatus + "]";
	}
    
    
}