package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import org.hibernate.validator.constraints.NotEmpty;

public class ExpressfeeType implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.first_count
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.expressfeetype.firstCount.validation.notempty}")
	private Integer firstCount;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.first_fee
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.expressfeetype.firstFee.validation.notempty}")
	private BigDecimal firstFee;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.add_count
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.expressfeetype.addCount.validation.notempty}")
	private Integer addCount;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.add_fee
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.expressfeetype.addFee.validation.notempty}")
	private BigDecimal addFee;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.expressfee_template_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.expressfeetype.expressfeeTemplateId.validation.notempty}")
	private Integer expressfeeTemplateId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.id
	 * @return  the value of b2b_expressfee_type.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.id
	 * @param id  the value for b2b_expressfee_type.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.first_count
	 * @return  the value of b2b_expressfee_type.first_count
	 * @mbggenerated
	 */
	public Integer getFirstCount() {
		return firstCount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.first_count
	 * @param firstCount  the value for b2b_expressfee_type.first_count
	 * @mbggenerated
	 */
	public void setFirstCount(Integer firstCount) {
		this.firstCount = firstCount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.first_fee
	 * @return  the value of b2b_expressfee_type.first_fee
	 * @mbggenerated
	 */
	public BigDecimal getFirstFee() {
		return firstFee;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.first_fee
	 * @param firstFee  the value for b2b_expressfee_type.first_fee
	 * @mbggenerated
	 */
	public void setFirstFee(BigDecimal firstFee) {
		this.firstFee = firstFee;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.add_count
	 * @return  the value of b2b_expressfee_type.add_count
	 * @mbggenerated
	 */
	public Integer getAddCount() {
		return addCount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.add_count
	 * @param addCount  the value for b2b_expressfee_type.add_count
	 * @mbggenerated
	 */
	public void setAddCount(Integer addCount) {
		this.addCount = addCount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.add_fee
	 * @return  the value of b2b_expressfee_type.add_fee
	 * @mbggenerated
	 */
	public BigDecimal getAddFee() {
		return addFee;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.add_fee
	 * @param addFee  the value for b2b_expressfee_type.add_fee
	 * @mbggenerated
	 */
	public void setAddFee(BigDecimal addFee) {
		this.addFee = addFee;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.expressfee_template_id
	 * @return  the value of b2b_expressfee_type.expressfee_template_id
	 * @mbggenerated
	 */
	public Integer getExpressfeeTemplateId() {
		return expressfeeTemplateId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_type.expressfee_template_id
	 * @param expressfeeTemplateId  the value for b2b_expressfee_type.expressfee_template_id
	 * @mbggenerated
	 */
	public void setExpressfeeTemplateId(Integer expressfeeTemplateId) {
		this.expressfeeTemplateId = expressfeeTemplateId;
	}

	private ExpressAddress expressAddress;

    public ExpressAddress getExpressAddress() {
		return expressAddress;
	}

	public void setExpressAddress(ExpressAddress expressAddress) {
		this.expressAddress = expressAddress;
	}
}