package com.i9he.m2b.model;

import java.io.Serializable;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class ExpressAddress implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.province_name
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.expressaddress.provinceName.validation.notempty}")
    @Length(message = "{m2b.expressaddress.provinceName.validation.length}", max = 50)
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.city_id
     *
     * @mbggenerated
     */
    @Length(message = "{m2b.expressaddress.cityId.validation.length}", max = 255)
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.expressfee_type_id
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.expressaddress.expressfeeTypeId.validation.notempty}")
    private Integer expressfeeTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.id
     *
     * @return the value of b2b_express_address.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.id
     *
     * @param id the value for b2b_express_address.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.province_name
     *
     * @return the value of b2b_express_address.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.province_name
     *
     * @param provinceName the value for b2b_express_address.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.city_id
     *
     * @return the value of b2b_express_address.city_id
     *
     * @mbggenerated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.city_id
     *
     * @param cityId the value for b2b_express_address.city_id
     *
     * @mbggenerated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.expressfee_type_id
     *
     * @return the value of b2b_express_address.expressfee_type_id
     *
     * @mbggenerated
     */
    public Integer getExpressfeeTypeId() {
        return expressfeeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_express_address.expressfee_type_id
     *
     * @param expressfeeTypeId the value for b2b_express_address.expressfee_type_id
     *
     * @mbggenerated
     */
    public void setExpressfeeTypeId(Integer expressfeeTypeId) {
        this.expressfeeTypeId = expressfeeTypeId;
    }
}