package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class ExpressfeeTemplate implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.name
	 * @mbggenerated
	 */
	@Length(message = "{m2b.expressfeetemplate.name.validation.length}", max = 50)
	private String name;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.express_name
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.expressfeetemplate.expressName.validation.notempty}")
	@Length(message = "{m2b.expressfeetemplate.expressName.validation.length}", max = 50)
	private String expressName;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.sender_province
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.expressfeetemplate.senderProvince.validation.notempty}")
	@Length(message = "{m2b.expressfeetemplate.senderProvince.validation.length}", max = 50)
	private String senderProvince;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.sender_city
	 * @mbggenerated
	 */
	@Length(message = "{m2b.expressfeetemplate.senderCity.validation.length}", max = 50)
	private String senderCity;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.express_type
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.expressfeetemplate.expressType.validation.notempty}")
	private Integer expressType;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.is_used
	 * @mbggenerated
	 */
	private Byte isUsed;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.expressfeetemplate.createTime.validation.notempty}")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.update_time
	 * @mbggenerated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.remark
	 * @mbggenerated
	 */
	@Length(message = "{m2b.expressfeetemplate.remark.validation.length}", max = 255)
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.id
	 * @return  the value of b2b_expressfee_template.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.id
	 * @param id  the value for b2b_expressfee_template.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.name
	 * @return  the value of b2b_expressfee_template.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.name
	 * @param name  the value for b2b_expressfee_template.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.express_name
	 * @return  the value of b2b_expressfee_template.express_name
	 * @mbggenerated
	 */
	public String getExpressName() {
		return expressName;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.express_name
	 * @param expressName  the value for b2b_expressfee_template.express_name
	 * @mbggenerated
	 */
	public void setExpressName(String expressName) {
		this.expressName = expressName == null ? null : expressName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.sender_province
	 * @return  the value of b2b_expressfee_template.sender_province
	 * @mbggenerated
	 */
	public String getSenderProvince() {
		return senderProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.sender_province
	 * @param senderProvince  the value for b2b_expressfee_template.sender_province
	 * @mbggenerated
	 */
	public void setSenderProvince(String senderProvince) {
		this.senderProvince = senderProvince == null ? null : senderProvince
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.sender_city
	 * @return  the value of b2b_expressfee_template.sender_city
	 * @mbggenerated
	 */
	public String getSenderCity() {
		return senderCity;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.sender_city
	 * @param senderCity  the value for b2b_expressfee_template.sender_city
	 * @mbggenerated
	 */
	public void setSenderCity(String senderCity) {
		this.senderCity = senderCity == null ? null : senderCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.express_type
	 * @return  the value of b2b_expressfee_template.express_type
	 * @mbggenerated
	 */
	public Integer getExpressType() {
		return expressType;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.express_type
	 * @param expressType  the value for b2b_expressfee_template.express_type
	 * @mbggenerated
	 */
	public void setExpressType(Integer expressType) {
		this.expressType = expressType;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.is_used
	 * @return  the value of b2b_expressfee_template.is_used
	 * @mbggenerated
	 */
	public Byte getIsUsed() {
		return isUsed;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.is_used
	 * @param isUsed  the value for b2b_expressfee_template.is_used
	 * @mbggenerated
	 */
	public void setIsUsed(Byte isUsed) {
		this.isUsed = isUsed;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.create_time
	 * @return  the value of b2b_expressfee_template.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.create_time
	 * @param createTime  the value for b2b_expressfee_template.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.update_time
	 * @return  the value of b2b_expressfee_template.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.update_time
	 * @param updateTime  the value for b2b_expressfee_template.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.remark
	 * @return  the value of b2b_expressfee_template.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_expressfee_template.remark
	 * @param remark  the value for b2b_expressfee_template.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}