package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.validator.constraints.Length;

public class HistoryOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.orderid
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.return_money
     *
     * @mbggenerated
     */
    @Length(message = "{m2b.historyorder.returnMoney.validation.length}", max = 20)
    private String returnMoney;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.tomoney
     *
     * @mbggenerated
     */
    private Date tomoney;
    
    private Date getmoneytime;
    
    

    public Date getGetmoneytime() {
		return getmoneytime;
	}

	public void setGetmoneytime(Date getmoneytime) {
		this.getmoneytime = getmoneytime;
	}

	/**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.order_time
     *
     * @mbggenerated
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    
    private Integer status;
    
    private Integer goodsId;
    
    
    

    public Integer getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.orderid
     *
     * @return the value of b2b_history_order.orderid
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.orderid
     *
     * @param orderid the value for b2b_history_order.orderid
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.user_id
     *
     * @return the value of b2b_history_order.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.user_id
     *
     * @param userId the value for b2b_history_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.amount
     *
     * @return the value of b2b_history_order.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.amount
     *
     * @param amount the value for b2b_history_order.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.return_money
     *
     * @return the value of b2b_history_order.return_money
     *
     * @mbggenerated
     */
    public String getReturnMoney() {
        return returnMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.return_money
     *
     * @param returnMoney the value for b2b_history_order.return_money
     *
     * @mbggenerated
     */
    public void setReturnMoney(String returnMoney) {
        this.returnMoney = returnMoney == null ? null : returnMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.tomoney
     *
     * @return the value of b2b_history_order.tomoney
     *
     * @mbggenerated
     */
    public Date getTomoney() {
        return tomoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.tomoney
     *
     * @param tomoney the value for b2b_history_order.tomoney
     *
     * @mbggenerated
     */
    public void setTomoney(Date tomoney) {
        this.tomoney = tomoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.order_time
     *
     * @return the value of b2b_history_order.order_time
     *
     * @mbggenerated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_history_order.order_time
     *
     * @param orderTime the value for b2b_history_order.order_time
     *
     * @mbggenerated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }
}