package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class InvoiceQualifed implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.user_id
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.invoicequalifed.userId.validation.notempty}")
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.organization
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.invoicequalifed.organization.validation.notempty}")
    @Length(message = "{m2b.invoicequalifed.organization.validation.length}", max = 50)
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.user_idcode
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.invoicequalifed.userIdcode.validation.notempty}")
    @Length(message = "{m2b.invoicequalifed.userIdcode.validation.length}", max = 50)
    private String userIdcode;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.regist_address
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.invoicequalifed.registAddress.validation.notempty}")
    @Length(message = "{m2b.invoicequalifed.registAddress.validation.length}", max = 255)
    private String registAddress;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.regist_phone
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.invoicequalifed.registPhone.validation.notempty}")
    @Length(message = "{m2b.invoicequalifed.registPhone.validation.length}", max = 30)
    private String registPhone;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.bank
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.invoicequalifed.bank.validation.notempty}")
    @Length(message = "{m2b.invoicequalifed.bank.validation.length}", max = 30)
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.bank_account
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.invoicequalifed.bankAccount.validation.notempty}")
    @Length(message = "{m2b.invoicequalifed.bankAccount.validation.length}", max = 30)
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.is_review
     *
     * @mbggenerated
     */
    private Byte isReview;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.review_result
     *
     * @mbggenerated
     */
    private Byte reviewResult;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.review_time
     *
     * @mbggenerated
     */
    private Date reviewTime;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.created_time
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.invoicequalifed.createdTime.validation.notempty}")
    private Date createdTime;

	/**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.id
     *
     * @return the value of b2b_invoice_qualifed.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.id
     *
     * @param id the value for b2b_invoice_qualifed.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.user_id
     *
     * @return the value of b2b_invoice_qualifed.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.user_id
     *
     * @param userId the value for b2b_invoice_qualifed.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.organization
     *
     * @return the value of b2b_invoice_qualifed.organization
     *
     * @mbggenerated
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.organization
     *
     * @param organization the value for b2b_invoice_qualifed.organization
     *
     * @mbggenerated
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.user_idcode
     *
     * @return the value of b2b_invoice_qualifed.user_idcode
     *
     * @mbggenerated
     */
    public String getUserIdcode() {
        return userIdcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.user_idcode
     *
     * @param userIdcode the value for b2b_invoice_qualifed.user_idcode
     *
     * @mbggenerated
     */
    public void setUserIdcode(String userIdcode) {
        this.userIdcode = userIdcode == null ? null : userIdcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.regist_address
     *
     * @return the value of b2b_invoice_qualifed.regist_address
     *
     * @mbggenerated
     */
    public String getRegistAddress() {
        return registAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.regist_address
     *
     * @param registAddress the value for b2b_invoice_qualifed.regist_address
     *
     * @mbggenerated
     */
    public void setRegistAddress(String registAddress) {
        this.registAddress = registAddress == null ? null : registAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.regist_phone
     *
     * @return the value of b2b_invoice_qualifed.regist_phone
     *
     * @mbggenerated
     */
    public String getRegistPhone() {
        return registPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.regist_phone
     *
     * @param registPhone the value for b2b_invoice_qualifed.regist_phone
     *
     * @mbggenerated
     */
    public void setRegistPhone(String registPhone) {
        this.registPhone = registPhone == null ? null : registPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.bank
     *
     * @return the value of b2b_invoice_qualifed.bank
     *
     * @mbggenerated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.bank
     *
     * @param bank the value for b2b_invoice_qualifed.bank
     *
     * @mbggenerated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.bank_account
     *
     * @return the value of b2b_invoice_qualifed.bank_account
     *
     * @mbggenerated
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.bank_account
     *
     * @param bankAccount the value for b2b_invoice_qualifed.bank_account
     *
     * @mbggenerated
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.is_review
     *
     * @return the value of b2b_invoice_qualifed.is_review
     *
     * @mbggenerated
     */
    public Byte getIsReview() {
        return isReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.is_review
     *
     * @param isReview the value for b2b_invoice_qualifed.is_review
     *
     * @mbggenerated
     */
    public void setIsReview(Byte isReview) {
        this.isReview = isReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.review_result
     *
     * @return the value of b2b_invoice_qualifed.review_result
     *
     * @mbggenerated
     */
    public Byte getReviewResult() {
        return reviewResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.review_result
     *
     * @param reviewResult the value for b2b_invoice_qualifed.review_result
     *
     * @mbggenerated
     */
    public void setReviewResult(Byte reviewResult) {
        this.reviewResult = reviewResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.review_time
     *
     * @return the value of b2b_invoice_qualifed.review_time
     *
     * @mbggenerated
     */
    public Date getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.review_time
     *
     * @param reviewTime the value for b2b_invoice_qualifed.review_time
     *
     * @mbggenerated
     */
    public void setReviewTime(Date reviewTime) {
        this.reviewTime = reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.created_time
     *
     * @return the value of b2b_invoice_qualifed.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_invoice_qualifed.created_time
     *
     * @param createdTime the value for b2b_invoice_qualifed.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}