package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class Loan implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.orderid
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.loan.orderid.validation.notempty}")
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.orderamount
     *
     * @mbggenerated
     */
    private BigDecimal orderamount;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.ordertime
     *
     * @mbggenerated
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.user_id
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.loan.userId.validation.notempty}")
    @Length(message = "{m2b.loan.userId.validation.length}", max = 50)
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.loanid
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.loan.loanid.validation.notempty}")
    @Length(message = "{m2b.loan.loanid.validation.length}", max = 50)
    private String loanid;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.state
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.loan.state.validation.notempty}")
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.getmoneytime
     *
     * @mbggenerated
     */
    private Date getmoneytime;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.create_time
     *
     * @mbggenerated
     */
    private Date createTime;
    
    private Date return_money;
    
    private Date tomoney;
    
    private BigDecimal balance;
    
    private Integer status;
    
    
    

    public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getReturn_money() {
		return return_money;
	}

	public void setReturn_money(Date return_money) {
		this.return_money = return_money;
	}

	public Date getTomoney() {
		return tomoney;
	}

	public void setTomoney(Date tomoney) {
		this.tomoney = tomoney;
	}

	public BigDecimal getBalance() {
		return balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	/**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.id
     *
     * @return the value of b2b_sy_loan.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.id
     *
     * @param id the value for b2b_sy_loan.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.orderid
     *
     * @return the value of b2b_sy_loan.orderid
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.orderid
     *
     * @param orderid the value for b2b_sy_loan.orderid
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.orderamount
     *
     * @return the value of b2b_sy_loan.orderamount
     *
     * @mbggenerated
     */
    public BigDecimal getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.orderamount
     *
     * @param orderamount the value for b2b_sy_loan.orderamount
     *
     * @mbggenerated
     */
    public void setOrderamount(BigDecimal orderamount) {
        this.orderamount = orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.ordertime
     *
     * @return the value of b2b_sy_loan.ordertime
     *
     * @mbggenerated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.ordertime
     *
     * @param ordertime the value for b2b_sy_loan.ordertime
     *
     * @mbggenerated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.user_id
     *
     * @return the value of b2b_sy_loan.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.user_id
     *
     * @param userId the value for b2b_sy_loan.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.loanid
     *
     * @return the value of b2b_sy_loan.loanid
     *
     * @mbggenerated
     */
    public String getLoanid() {
        return loanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.loanid
     *
     * @param loanid the value for b2b_sy_loan.loanid
     *
     * @mbggenerated
     */
    public void setLoanid(String loanid) {
        this.loanid = loanid == null ? null : loanid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.state
     *
     * @return the value of b2b_sy_loan.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.state
     *
     * @param state the value for b2b_sy_loan.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.getmoneytime
     *
     * @return the value of b2b_sy_loan.getmoneytime
     *
     * @mbggenerated
     */
    public Date getGetmoneytime() {
        return getmoneytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.getmoneytime
     *
     * @param getmoneytime the value for b2b_sy_loan.getmoneytime
     *
     * @mbggenerated
     */
    public void setGetmoneytime(Date getmoneytime) {
        this.getmoneytime = getmoneytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.create_time
     *
     * @return the value of b2b_sy_loan.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_sy_loan.create_time
     *
     * @param createTime the value for b2b_sy_loan.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}