package com.i9he.m2b.model;

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class LogisticsInfo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.shipper_code
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.logisticsinfo.shipperCode.validation.notempty}")
	@Length(message = "{m2b.logisticsinfo.shipperCode.validation.length}", max = 20)
	private String shipperCode;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.logistic_code
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.logisticsinfo.logisticCode.validation.notempty}")
	@Length(message = "{m2b.logisticsinfo.logisticCode.validation.length}", max = 50)
	private String logisticCode;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.state
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.logisticsinfo.state.validation.notempty}")
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.estimated_delivery_time
	 * @mbggenerated
	 */
	private Date estimatedDeliveryTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.push_time
	 * @mbggenerated
	 */
	private Date pushTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.id
	 * @return  the value of b2b_logistics_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.id
	 * @param id  the value for b2b_logistics_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.shipper_code
	 * @return  the value of b2b_logistics_info.shipper_code
	 * @mbggenerated
	 */
	public String getShipperCode() {
		return shipperCode;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.shipper_code
	 * @param shipperCode  the value for b2b_logistics_info.shipper_code
	 * @mbggenerated
	 */
	public void setShipperCode(String shipperCode) {
		this.shipperCode = shipperCode == null ? null : shipperCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.logistic_code
	 * @return  the value of b2b_logistics_info.logistic_code
	 * @mbggenerated
	 */
	public String getLogisticCode() {
		return logisticCode;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.logistic_code
	 * @param logisticCode  the value for b2b_logistics_info.logistic_code
	 * @mbggenerated
	 */
	public void setLogisticCode(String logisticCode) {
		this.logisticCode = logisticCode == null ? null : logisticCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.state
	 * @return  the value of b2b_logistics_info.state
	 * @mbggenerated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.state
	 * @param state  the value for b2b_logistics_info.state
	 * @mbggenerated
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.estimated_delivery_time
	 * @return  the value of b2b_logistics_info.estimated_delivery_time
	 * @mbggenerated
	 */
	public Date getEstimatedDeliveryTime() {
		return estimatedDeliveryTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.estimated_delivery_time
	 * @param estimatedDeliveryTime  the value for b2b_logistics_info.estimated_delivery_time
	 * @throws ParseException 
	 * @mbggenerated
	 */
	public void setEstimatedDeliveryTime(String estimatedDeliveryTime) throws ParseException {
		SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd HH:mm");
		this.estimatedDeliveryTime = sdf1.parse(estimatedDeliveryTime);
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.push_time
	 * @return  the value of b2b_logistics_info.push_time
	 * @mbggenerated
	 */
	public Date getPushTime() {
		return pushTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_logistics_info.push_time
	 * @param pushTime  the value for b2b_logistics_info.push_time
	 * @mbggenerated
	 */
	public void setPushTime(Date pushTime) {
		this.pushTime = pushTime;
	}
}