package com.i9he.m2b.model;

import java.io.Serializable;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class MessageType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype.name
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.messagetype.name.validation.notempty}")
    @Length(message = "{m2b.messagetype.name.validation.length}", max = 50)
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype.orderNo
     *
     * @mbggenerated
     */
    private Integer orderno;
    
    private Integer typeNum;
    
    

    public Integer getTypeNum() {
		return typeNum;
	}

	public void setTypeNum(Integer typeNum) {
		this.typeNum = typeNum;
	}

	/**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype.id
     *
     * @return the value of b2b_messagetype.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype.id
     *
     * @param id the value for b2b_messagetype.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype.name
     *
     * @return the value of b2b_messagetype.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype.name
     *
     * @param name the value for b2b_messagetype.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype.orderNo
     *
     * @return the value of b2b_messagetype.orderNo
     *
     * @mbggenerated
     */
    public Integer getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_messagetype.orderNo
     *
     * @param orderno the value for b2b_messagetype.orderNo
     *
     * @mbggenerated
     */
    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }
}