package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class Message implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.title
	 * @mbggenerated
	 */
	@Length(message = "{m2b.message.title.validation.length}", max = 50)
	private String title;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.content
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.message.content.validation.notempty}")
	@Length(message = "{m2b.message.content.validation.length}", max = 500)
	private String content;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.image
	 * @mbggenerated
	 */
	@Length(message = "{m2b.message.image.validation.length}", max = 100)
	private String image;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.message.userId.validation.notempty}")
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.is_read
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.message.isRead.validation.notempty}")
	private Byte isRead;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.is_receive
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.message.isReceive.validation.notempty}")
	private Byte isReceive;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.message.createTime.validation.notempty}")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.url
	 * @mbggenerated
	 */
	@Length(message = "{m2b.message.url.validation.length}", max = 255)
	private String url;
	
	private String name;
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_message
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.id
	 * @return  the value of b2b_message.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.id
	 * @param id  the value for b2b_message.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.title
	 * @return  the value of b2b_message.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.title
	 * @param title  the value for b2b_message.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.content
	 * @return  the value of b2b_message.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.content
	 * @param content  the value for b2b_message.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.image
	 * @return  the value of b2b_message.image
	 * @mbggenerated
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.image
	 * @param image  the value for b2b_message.image
	 * @mbggenerated
	 */
	public void setImage(String image) {
		this.image = image == null ? null : image.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.user_id
	 * @return  the value of b2b_message.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.user_id
	 * @param userId  the value for b2b_message.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.is_read
	 * @return  the value of b2b_message.is_read
	 * @mbggenerated
	 */
	public Byte getIsRead() {
		return isRead;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.is_read
	 * @param isRead  the value for b2b_message.is_read
	 * @mbggenerated
	 */
	public void setIsRead(Byte isRead) {
		this.isRead = isRead;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.is_receive
	 * @return  the value of b2b_message.is_receive
	 * @mbggenerated
	 */
	public Byte getIsReceive() {
		return isReceive;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.is_receive
	 * @param isReceive  the value for b2b_message.is_receive
	 * @mbggenerated
	 */
	public void setIsReceive(Byte isReceive) {
		this.isReceive = isReceive;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.create_time
	 * @return  the value of b2b_message.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.create_time
	 * @param createTime  the value for b2b_message.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.url
	 * @return  the value of b2b_message.url
	 * @mbggenerated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_message.url
	 * @param url  the value for b2b_message.url
	 * @mbggenerated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}
}