package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class PurchaseRequirement implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.title
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirement.title.validation.length}", max = 255)
	private String title;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.type
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.purchaserequirement.type.validation.notempty}")
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.state
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.purchaserequirement.state.validation.notempty}")
	private Byte state;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.user_id
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.contact
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirement.contact.validation.length}", max = 50)
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.phone
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirement.phone.validation.length}", max = 50)
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.email
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirement.email.validation.length}", max = 50)
	private String email;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.qq
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirement.qq.validation.length}", max = 50)
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.weixin
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirement.weixin.validation.length}", max = 50)
	private String weixin;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.company
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirement.company.validation.length}", max = 255)
	private String company;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.description
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirement.description.validation.length}", max = 5000)
	private String description;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.remark
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirement.remark.validation.length}", max = 255)
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.purchaserequirement.createTime.validation.notempty}")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.id
	 * @return  the value of b2b_pur_requirement.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.id
	 * @param id  the value for b2b_pur_requirement.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.title
	 * @return  the value of b2b_pur_requirement.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.title
	 * @param title  the value for b2b_pur_requirement.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.type
	 * @return  the value of b2b_pur_requirement.type
	 * @mbggenerated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.type
	 * @param type  the value for b2b_pur_requirement.type
	 * @mbggenerated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.state
	 * @return  the value of b2b_pur_requirement.state
	 * @mbggenerated
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.state
	 * @param state  the value for b2b_pur_requirement.state
	 * @mbggenerated
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.user_id
	 * @return  the value of b2b_pur_requirement.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.user_id
	 * @param userId  the value for b2b_pur_requirement.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.contact
	 * @return  the value of b2b_pur_requirement.contact
	 * @mbggenerated
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.contact
	 * @param contact  the value for b2b_pur_requirement.contact
	 * @mbggenerated
	 */
	public void setContact(String contact) {
		this.contact = contact == null ? null : contact.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.phone
	 * @return  the value of b2b_pur_requirement.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.phone
	 * @param phone  the value for b2b_pur_requirement.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.email
	 * @return  the value of b2b_pur_requirement.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.email
	 * @param email  the value for b2b_pur_requirement.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.qq
	 * @return  the value of b2b_pur_requirement.qq
	 * @mbggenerated
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.qq
	 * @param qq  the value for b2b_pur_requirement.qq
	 * @mbggenerated
	 */
	public void setQq(String qq) {
		this.qq = qq == null ? null : qq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.weixin
	 * @return  the value of b2b_pur_requirement.weixin
	 * @mbggenerated
	 */
	public String getWeixin() {
		return weixin;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.weixin
	 * @param weixin  the value for b2b_pur_requirement.weixin
	 * @mbggenerated
	 */
	public void setWeixin(String weixin) {
		this.weixin = weixin == null ? null : weixin.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.company
	 * @return  the value of b2b_pur_requirement.company
	 * @mbggenerated
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.company
	 * @param company  the value for b2b_pur_requirement.company
	 * @mbggenerated
	 */
	public void setCompany(String company) {
		this.company = company == null ? null : company.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.description
	 * @return  the value of b2b_pur_requirement.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.description
	 * @param description  the value for b2b_pur_requirement.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.remark
	 * @return  the value of b2b_pur_requirement.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.remark
	 * @param remark  the value for b2b_pur_requirement.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.create_time
	 * @return  the value of b2b_pur_requirement.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement.create_time
	 * @param createTime  the value for b2b_pur_requirement.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}