package com.i9he.m2b.model;

import java.io.Serializable;
import org.hibernate.validator.constraints.Length;

public class PurchaseRequirementAddition implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.requirement_id
	 * @mbggenerated
	 */
	private Integer requirementId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.name
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirementaddition.name.validation.length}", max = 255)
	private String name;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.filename
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirementaddition.filename.validation.length}", max = 255)
	private String filename;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.id
	 * @return  the value of b2b_pur_requirement_addition.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.id
	 * @param id  the value for b2b_pur_requirement_addition.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.requirement_id
	 * @return  the value of b2b_pur_requirement_addition.requirement_id
	 * @mbggenerated
	 */
	public Integer getRequirementId() {
		return requirementId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.requirement_id
	 * @param requirementId  the value for b2b_pur_requirement_addition.requirement_id
	 * @mbggenerated
	 */
	public void setRequirementId(Integer requirementId) {
		this.requirementId = requirementId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.name
	 * @return  the value of b2b_pur_requirement_addition.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.name
	 * @param name  the value for b2b_pur_requirement_addition.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.filename
	 * @return  the value of b2b_pur_requirement_addition.filename
	 * @mbggenerated
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_addition.filename
	 * @param filename  the value for b2b_pur_requirement_addition.filename
	 * @mbggenerated
	 */
	public void setFilename(String filename) {
		this.filename = filename == null ? null : filename.trim();
	}
}