package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class PurchaseRequirementOffer implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.requirement_id
	 * @mbggenerated
	 */
	private Integer requirementId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.goods_name
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.purchaserequirementoffer.goodsName.validation.notempty}")
	@Length(message = "{m2b.purchaserequirementoffer.goodsName.validation.length}", max = 255)
	private String goodsName;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.goods_url
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirementoffer.goodsUrl.validation.length}", max = 255)
	private String goodsUrl;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.reason
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirementoffer.reason.validation.length}", max = 255)
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.goods_value
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirementoffer.goodsValue.validation.length}", max = 255)
	private String goodsValue;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.price
	 * @mbggenerated
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.service
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirementoffer.service.validation.length}", max = 50)
	private String service;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.phone
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirementoffer.phone.validation.length}", max = 50)
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.purchaserequirementoffer.createTime.validation.notempty}")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.create_user
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.purchaserequirementoffer.createUser.validation.notempty}")
	private Integer createUser;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.update_time
	 * @mbggenerated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.update_user
	 * @mbggenerated
	 */
	private Integer updateUser;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.id
	 * @return  the value of b2b_pur_requirement_offer.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.id
	 * @param id  the value for b2b_pur_requirement_offer.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.requirement_id
	 * @return  the value of b2b_pur_requirement_offer.requirement_id
	 * @mbggenerated
	 */
	public Integer getRequirementId() {
		return requirementId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.requirement_id
	 * @param requirementId  the value for b2b_pur_requirement_offer.requirement_id
	 * @mbggenerated
	 */
	public void setRequirementId(Integer requirementId) {
		this.requirementId = requirementId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.goods_name
	 * @return  the value of b2b_pur_requirement_offer.goods_name
	 * @mbggenerated
	 */
	public String getGoodsName() {
		return goodsName;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.goods_name
	 * @param goodsName  the value for b2b_pur_requirement_offer.goods_name
	 * @mbggenerated
	 */
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName == null ? null : goodsName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.goods_url
	 * @return  the value of b2b_pur_requirement_offer.goods_url
	 * @mbggenerated
	 */
	public String getGoodsUrl() {
		return goodsUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.goods_url
	 * @param goodsUrl  the value for b2b_pur_requirement_offer.goods_url
	 * @mbggenerated
	 */
	public void setGoodsUrl(String goodsUrl) {
		this.goodsUrl = goodsUrl == null ? null : goodsUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.reason
	 * @return  the value of b2b_pur_requirement_offer.reason
	 * @mbggenerated
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.reason
	 * @param reason  the value for b2b_pur_requirement_offer.reason
	 * @mbggenerated
	 */
	public void setReason(String reason) {
		this.reason = reason == null ? null : reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.goods_value
	 * @return  the value of b2b_pur_requirement_offer.goods_value
	 * @mbggenerated
	 */
	public String getGoodsValue() {
		return goodsValue;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.goods_value
	 * @param goodsValue  the value for b2b_pur_requirement_offer.goods_value
	 * @mbggenerated
	 */
	public void setGoodsValue(String goodsValue) {
		this.goodsValue = goodsValue == null ? null : goodsValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.price
	 * @return  the value of b2b_pur_requirement_offer.price
	 * @mbggenerated
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.price
	 * @param price  the value for b2b_pur_requirement_offer.price
	 * @mbggenerated
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.service
	 * @return  the value of b2b_pur_requirement_offer.service
	 * @mbggenerated
	 */
	public String getService() {
		return service;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.service
	 * @param service  the value for b2b_pur_requirement_offer.service
	 * @mbggenerated
	 */
	public void setService(String service) {
		this.service = service == null ? null : service.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.phone
	 * @return  the value of b2b_pur_requirement_offer.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.phone
	 * @param phone  the value for b2b_pur_requirement_offer.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.create_time
	 * @return  the value of b2b_pur_requirement_offer.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.create_time
	 * @param createTime  the value for b2b_pur_requirement_offer.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.create_user
	 * @return  the value of b2b_pur_requirement_offer.create_user
	 * @mbggenerated
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.create_user
	 * @param createUser  the value for b2b_pur_requirement_offer.create_user
	 * @mbggenerated
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.update_time
	 * @return  the value of b2b_pur_requirement_offer.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.update_time
	 * @param updateTime  the value for b2b_pur_requirement_offer.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.update_user
	 * @return  the value of b2b_pur_requirement_offer.update_user
	 * @mbggenerated
	 */
	public Integer getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_offer.update_user
	 * @param updateUser  the value for b2b_pur_requirement_offer.update_user
	 * @mbggenerated
	 */
	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}
}