package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import org.hibernate.validator.constraints.Length;

public class PurchaseRequirementGoods implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.requirement_id
	 * @mbggenerated
	 */
	private Integer requirementId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.goods_name
	 * @mbggenerated
	 */
	@Length(message = "{m2b.purchaserequirementgoods.goodsName.validation.length}", max = 255)
	private String goodsName;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.qty
	 * @mbggenerated
	 */
	private Integer qty;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.budget
	 * @mbggenerated
	 */
	private BigDecimal budget;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.id
	 * @return  the value of b2b_pur_requirement_goods.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.id
	 * @param id  the value for b2b_pur_requirement_goods.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.requirement_id
	 * @return  the value of b2b_pur_requirement_goods.requirement_id
	 * @mbggenerated
	 */
	public Integer getRequirementId() {
		return requirementId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.requirement_id
	 * @param requirementId  the value for b2b_pur_requirement_goods.requirement_id
	 * @mbggenerated
	 */
	public void setRequirementId(Integer requirementId) {
		this.requirementId = requirementId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.goods_name
	 * @return  the value of b2b_pur_requirement_goods.goods_name
	 * @mbggenerated
	 */
	public String getGoodsName() {
		return goodsName;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.goods_name
	 * @param goodsName  the value for b2b_pur_requirement_goods.goods_name
	 * @mbggenerated
	 */
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName == null ? null : goodsName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.qty
	 * @return  the value of b2b_pur_requirement_goods.qty
	 * @mbggenerated
	 */
	public Integer getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.qty
	 * @param qty  the value for b2b_pur_requirement_goods.qty
	 * @mbggenerated
	 */
	public void setQty(Integer qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.budget
	 * @return  the value of b2b_pur_requirement_goods.budget
	 * @mbggenerated
	 */
	public BigDecimal getBudget() {
		return budget;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_pur_requirement_goods.budget
	 * @param budget  the value for b2b_pur_requirement_goods.budget
	 * @mbggenerated
	 */
	public void setBudget(BigDecimal budget) {
		this.budget = budget;
	}
}