package com.i9he.m2b.model;

import java.io.Serializable;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class SeoParams implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.seo_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.seoparams.seoId.validation.notempty}")
	private Integer seoId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.name
	 * @mbggenerated
	 */
	@Length(message = "{m2b.seoparams.name.validation.length}", max = 255)
	private String name;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.value
	 * @mbggenerated
	 */
	@Length(message = "{m2b.seoparams.value.validation.length}", max = 255)
	private String value;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.id
	 * @return  the value of b2b_seo_params.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.id
	 * @param id  the value for b2b_seo_params.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.seo_id
	 * @return  the value of b2b_seo_params.seo_id
	 * @mbggenerated
	 */
	public Integer getSeoId() {
		return seoId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.seo_id
	 * @param seoId  the value for b2b_seo_params.seo_id
	 * @mbggenerated
	 */
	public void setSeoId(Integer seoId) {
		this.seoId = seoId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.name
	 * @return  the value of b2b_seo_params.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.name
	 * @param name  the value for b2b_seo_params.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.value
	 * @return  the value of b2b_seo_params.value
	 * @mbggenerated
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_seo_params.value
	 * @param value  the value for b2b_seo_params.value
	 * @mbggenerated
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}
}