package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class SerialNumber implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.goodsid
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.serialnumber.goodsid.validation.notempty}")
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.b2b_serial
     *
     * @mbggenerated
     */
    @Length(message = "{m2b.serialnumber.b2bSerial.validation.length}", max = 30)
    private String b2bSerial;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.manufacturer_serial
     *
     * @mbggenerated
     */
    @Length(message = "{m2b.serialnumber.manufacturerSerial.validation.length}", max = 30)
    private String manufacturerSerial;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.create_man
     *
     * @mbggenerated
     */
    private Integer createMan;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.update_man
     *
     * @mbggenerated
     */
    private Integer updateMan;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;
    
    private String type;
    
    private String name;
    
    

    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.id
     *
     * @return the value of b2b_serial_number.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.id
     *
     * @param id the value for b2b_serial_number.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.goodsid
     *
     * @return the value of b2b_serial_number.goodsid
     *
     * @mbggenerated
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.b2b_serial
     *
     * @return the value of b2b_serial_number.b2b_serial
     *
     * @mbggenerated
     */
    public String getB2bSerial() {
        return b2bSerial;
    }

    public Integer getGoodsid() {
		return goodsid;
	}

	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.b2b_serial
     *
     * @param b2bSerial the value for b2b_serial_number.b2b_serial
     *
     * @mbggenerated
     */
    public void setB2bSerial(String b2bSerial) {
        this.b2bSerial = b2bSerial == null ? null : b2bSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.manufacturer_serial
     *
     * @return the value of b2b_serial_number.manufacturer_serial
     *
     * @mbggenerated
     */
    public String getManufacturerSerial() {
        return manufacturerSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.manufacturer_serial
     *
     * @param manufacturerSerial the value for b2b_serial_number.manufacturer_serial
     *
     * @mbggenerated
     */
    public void setManufacturerSerial(String manufacturerSerial) {
        this.manufacturerSerial = manufacturerSerial == null ? null : manufacturerSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.create_man
     *
     * @return the value of b2b_serial_number.create_man
     *
     * @mbggenerated
     */
    public Integer getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.create_man
     *
     * @param createMan the value for b2b_serial_number.create_man
     *
     * @mbggenerated
     */
    public void setCreateMan(Integer createMan) {
        this.createMan = createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.create_time
     *
     * @return the value of b2b_serial_number.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.create_time
     *
     * @param createTime the value for b2b_serial_number.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.update_man
     *
     * @return the value of b2b_serial_number.update_man
     *
     * @mbggenerated
     */
    public Integer getUpdateMan() {
        return updateMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.update_man
     *
     * @param updateMan the value for b2b_serial_number.update_man
     *
     * @mbggenerated
     */
    public void setUpdateMan(Integer updateMan) {
        this.updateMan = updateMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.update_time
     *
     * @return the value of b2b_serial_number.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_serial_number.update_time
     *
     * @param updateTime the value for b2b_serial_number.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}