package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class SyUser implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.syuser.userId.validation.notempty}")
	@Length(message = "{m2b.syuser.userId.validation.length}", max = 50)
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.balance
	 * @mbggenerated
	 */
	private BigDecimal balance;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.state
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.syuser.state.validation.notempty}")
	private Byte state;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.buserid
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.syuser.buserid.validation.notempty}")
	private Integer buserid;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.phone
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.syuser.phone.validation.notempty}")
	@Length(message = "{m2b.syuser.phone.validation.length}", max = 11)
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.enterprise_name
	 * @mbggenerated
	 */
	@Length(message = "{m2b.syuser.enterpriseName.validation.length}", max = 100)
	private String enterpriseName;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.legalperson
	 * @mbggenerated
	 */
	@Length(message = "{m2b.syuser.legalperson.validation.length}", max = 30)
	private String legalperson;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.idcard
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.syuser.idcard.validation.notempty}")
	@Length(message = "{m2b.syuser.idcard.validation.length}", max = 18)
	private String idcard;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.officephone
	 * @mbggenerated
	 */
	@Length(message = "{m2b.syuser.officephone.validation.length}", max = 20)
	private String officephone;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.staffcount
	 * @mbggenerated
	 */
	private Integer staffcount;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.card
	 * @mbggenerated
	 */
	private Byte card;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.binum
	 * @mbggenerated
	 */
	@Length(message = "{m2b.syuser.binum.validation.length}", max = 50)
	private String binum;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.org_code
	 * @mbggenerated
	 */
	@Length(message = "{m2b.syuser.orgCode.validation.length}", max = 50)
	private String orgCode;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.tax_card_num
	 * @mbggenerated
	 */
	@Length(message = "{m2b.syuser.taxCardNum.validation.length}", max = 100)
	private String taxCardNum;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.cardno
	 * @mbggenerated
	 */
	@Length(message = "{m2b.syuser.cardno.validation.length}", max = 50)
	private String cardno;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.sccardno
	 * @mbggenerated
	 */
	@Length(message = "{m2b.syuser.sccardno.validation.length}", max = 50)
	private String sccardno;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.id
	 * @return  the value of b2b_sy_user.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.id
	 * @param id  the value for b2b_sy_user.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.user_id
	 * @return  the value of b2b_sy_user.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.user_id
	 * @param userId  the value for b2b_sy_user.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.balance
	 * @return  the value of b2b_sy_user.balance
	 * @mbggenerated
	 */
	public BigDecimal getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.balance
	 * @param balance  the value for b2b_sy_user.balance
	 * @mbggenerated
	 */
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.state
	 * @return  the value of b2b_sy_user.state
	 * @mbggenerated
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.state
	 * @param state  the value for b2b_sy_user.state
	 * @mbggenerated
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.buserid
	 * @return  the value of b2b_sy_user.buserid
	 * @mbggenerated
	 */
	public Integer getBuserid() {
		return buserid;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.buserid
	 * @param buserid  the value for b2b_sy_user.buserid
	 * @mbggenerated
	 */
	public void setBuserid(Integer buserid) {
		this.buserid = buserid;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.phone
	 * @return  the value of b2b_sy_user.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.phone
	 * @param phone  the value for b2b_sy_user.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.enterprise_name
	 * @return  the value of b2b_sy_user.enterprise_name
	 * @mbggenerated
	 */
	public String getEnterpriseName() {
		return enterpriseName;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.enterprise_name
	 * @param enterpriseName  the value for b2b_sy_user.enterprise_name
	 * @mbggenerated
	 */
	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.legalperson
	 * @return  the value of b2b_sy_user.legalperson
	 * @mbggenerated
	 */
	public String getLegalperson() {
		return legalperson;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.legalperson
	 * @param legalperson  the value for b2b_sy_user.legalperson
	 * @mbggenerated
	 */
	public void setLegalperson(String legalperson) {
		this.legalperson = legalperson == null ? null : legalperson.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.idcard
	 * @return  the value of b2b_sy_user.idcard
	 * @mbggenerated
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.idcard
	 * @param idcard  the value for b2b_sy_user.idcard
	 * @mbggenerated
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard == null ? null : idcard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.officephone
	 * @return  the value of b2b_sy_user.officephone
	 * @mbggenerated
	 */
	public String getOfficephone() {
		return officephone;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.officephone
	 * @param officephone  the value for b2b_sy_user.officephone
	 * @mbggenerated
	 */
	public void setOfficephone(String officephone) {
		this.officephone = officephone == null ? null : officephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.staffcount
	 * @return  the value of b2b_sy_user.staffcount
	 * @mbggenerated
	 */
	public Integer getStaffcount() {
		return staffcount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.staffcount
	 * @param staffcount  the value for b2b_sy_user.staffcount
	 * @mbggenerated
	 */
	public void setStaffcount(Integer staffcount) {
		this.staffcount = staffcount;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.card
	 * @return  the value of b2b_sy_user.card
	 * @mbggenerated
	 */
	public Byte getCard() {
		return card;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.card
	 * @param card  the value for b2b_sy_user.card
	 * @mbggenerated
	 */
	public void setCard(Byte card) {
		this.card = card;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.binum
	 * @return  the value of b2b_sy_user.binum
	 * @mbggenerated
	 */
	public String getBinum() {
		return binum;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.binum
	 * @param binum  the value for b2b_sy_user.binum
	 * @mbggenerated
	 */
	public void setBinum(String binum) {
		this.binum = binum == null ? null : binum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.org_code
	 * @return  the value of b2b_sy_user.org_code
	 * @mbggenerated
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.org_code
	 * @param orgCode  the value for b2b_sy_user.org_code
	 * @mbggenerated
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode == null ? null : orgCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.tax_card_num
	 * @return  the value of b2b_sy_user.tax_card_num
	 * @mbggenerated
	 */
	public String getTaxCardNum() {
		return taxCardNum;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.tax_card_num
	 * @param taxCardNum  the value for b2b_sy_user.tax_card_num
	 * @mbggenerated
	 */
	public void setTaxCardNum(String taxCardNum) {
		this.taxCardNum = taxCardNum == null ? null : taxCardNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.cardno
	 * @return  the value of b2b_sy_user.cardno
	 * @mbggenerated
	 */
	public String getCardno() {
		return cardno;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.cardno
	 * @param cardno  the value for b2b_sy_user.cardno
	 * @mbggenerated
	 */
	public void setCardno(String cardno) {
		this.cardno = cardno == null ? null : cardno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.sccardno
	 * @return  the value of b2b_sy_user.sccardno
	 * @mbggenerated
	 */
	public String getSccardno() {
		return sccardno;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.sccardno
	 * @param sccardno  the value for b2b_sy_user.sccardno
	 * @mbggenerated
	 */
	public void setSccardno(String sccardno) {
		this.sccardno = sccardno == null ? null : sccardno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.create_time
	 * @return  the value of b2b_sy_user.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_sy_user.create_time
	 * @param createTime  the value for b2b_sy_user.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}