package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class Tag implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.name
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tag.name.validation.notempty}")
	@Length(message = "{m2b.tag.name.validation.length}", max = 50)
	private String name;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.type
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tag.type.validation.notempty}")
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.sort_no
	 * @mbggenerated
	 */
	private Integer sortNo;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tag.createTime.validation.notempty}")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.create_user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tag.createUserId.validation.notempty}")
	private Integer createUserId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.remark
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tag.remark.validation.notempty}")
	@Length(message = "{m2b.tag.remark.validation.length}", max = 255)
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.id
	 * @return  the value of b2b_tag.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.id
	 * @param id  the value for b2b_tag.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.name
	 * @return  the value of b2b_tag.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.name
	 * @param name  the value for b2b_tag.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.type
	 * @return  the value of b2b_tag.type
	 * @mbggenerated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.type
	 * @param type  the value for b2b_tag.type
	 * @mbggenerated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.sort_no
	 * @return  the value of b2b_tag.sort_no
	 * @mbggenerated
	 */
	public Integer getSortNo() {
		return sortNo;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.sort_no
	 * @param sortNo  the value for b2b_tag.sort_no
	 * @mbggenerated
	 */
	public void setSortNo(Integer sortNo) {
		this.sortNo = sortNo;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.create_time
	 * @return  the value of b2b_tag.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.create_time
	 * @param createTime  the value for b2b_tag.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.create_user_id
	 * @return  the value of b2b_tag.create_user_id
	 * @mbggenerated
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.create_user_id
	 * @param createUserId  the value for b2b_tag.create_user_id
	 * @mbggenerated
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.remark
	 * @return  the value of b2b_tag.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag.remark
	 * @param remark  the value for b2b_tag.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}