package com.i9he.m2b.model;

import java.io.Serializable;

public class TagCategoryMapping implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_cate_mapping.category_id
	 * @mbggenerated
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_cate_mapping.tag_id
	 * @mbggenerated
	 */
	private Integer tagId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_cate_mapping
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_cate_mapping.category_id
	 * @return  the value of b2b_tag_cate_mapping.category_id
	 * @mbggenerated
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_cate_mapping.category_id
	 * @param categoryId  the value for b2b_tag_cate_mapping.category_id
	 * @mbggenerated
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_cate_mapping.tag_id
	 * @return  the value of b2b_tag_cate_mapping.tag_id
	 * @mbggenerated
	 */
	public Integer getTagId() {
		return tagId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_cate_mapping.tag_id
	 * @param tagId  the value for b2b_tag_cate_mapping.tag_id
	 * @mbggenerated
	 */
	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}
}