package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class TagCategory implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.name
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tagcategory.name.validation.notempty}")
	@Length(message = "{m2b.tagcategory.name.validation.length}", max = 50)
	private String name;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.sort_no
	 * @mbggenerated
	 */
	private Integer sortNo;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tagcategory.createTime.validation.notempty}")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.create_user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tagcategory.createUserId.validation.notempty}")
	private Integer createUserId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.remark
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tagcategory.remark.validation.notempty}")
	@Length(message = "{m2b.tagcategory.remark.validation.length}", max = 255)
	private String remark;
	
	private List<Tag> tags;
	
	public List<Tag> getTags() {
		return tags;
	}

	public void setTags(List<Tag> tags) {
		this.tags = tags;
	}

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.id
	 * @return  the value of b2b_tag_category.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.id
	 * @param id  the value for b2b_tag_category.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.name
	 * @return  the value of b2b_tag_category.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.name
	 * @param name  the value for b2b_tag_category.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.sort_no
	 * @return  the value of b2b_tag_category.sort_no
	 * @mbggenerated
	 */
	public Integer getSortNo() {
		return sortNo;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.sort_no
	 * @param sortNo  the value for b2b_tag_category.sort_no
	 * @mbggenerated
	 */
	public void setSortNo(Integer sortNo) {
		this.sortNo = sortNo;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.create_time
	 * @return  the value of b2b_tag_category.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.create_time
	 * @param createTime  the value for b2b_tag_category.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.create_user_id
	 * @return  the value of b2b_tag_category.create_user_id
	 * @mbggenerated
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.create_user_id
	 * @param createUserId  the value for b2b_tag_category.create_user_id
	 * @mbggenerated
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.remark
	 * @return  the value of b2b_tag_category.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_category.remark
	 * @param remark  the value for b2b_tag_category.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}