package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.Length;

public class TagMapping implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.tag_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tagmapping.tagId.validation.notempty}")
	private Integer tagId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.type
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tagmapping.type.validation.notempty}")
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.target_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tagmapping.targetId.validation.notempty}")
	@Length(message = "{m2b.tagmapping.targetId.validation.length}", max = 50)
	private String targetId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tagmapping.createTime.validation.notempty}")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.create_user_id
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.tagmapping.createUserId.validation.notempty}")
	private Integer createUserId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.id
	 * @return  the value of b2b_tag_mapping.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.id
	 * @param id  the value for b2b_tag_mapping.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.tag_id
	 * @return  the value of b2b_tag_mapping.tag_id
	 * @mbggenerated
	 */
	public Integer getTagId() {
		return tagId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.tag_id
	 * @param tagId  the value for b2b_tag_mapping.tag_id
	 * @mbggenerated
	 */
	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.type
	 * @return  the value of b2b_tag_mapping.type
	 * @mbggenerated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.type
	 * @param type  the value for b2b_tag_mapping.type
	 * @mbggenerated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.target_id
	 * @return  the value of b2b_tag_mapping.target_id
	 * @mbggenerated
	 */
	public String getTargetId() {
		return targetId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.target_id
	 * @param targetId  the value for b2b_tag_mapping.target_id
	 * @mbggenerated
	 */
	public void setTargetId(String targetId) {
		this.targetId = targetId == null ? null : targetId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.create_time
	 * @return  the value of b2b_tag_mapping.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.create_time
	 * @param createTime  the value for b2b_tag_mapping.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.create_user_id
	 * @return  the value of b2b_tag_mapping.create_user_id
	 * @mbggenerated
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_tag_mapping.create_user_id
	 * @param createUserId  the value for b2b_tag_mapping.create_user_id
	 * @mbggenerated
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}
}