package com.i9he.m2b.model;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class UserExpand implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.user_id
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.company
	 * @mbggenerated
	 */
	@Length(message = "{m2b.userexpand.company.validation.length}", max = 30)
	private String company;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.birthday
	 * @mbggenerated
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.job
	 * @mbggenerated
	 */
	@Length(message = "{m2b.userexpand.job.validation.length}", max = 20)
	private String job;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.qqjcb
	 * @mbggenerated
	 */
	private Integer qqjcb;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.wxjcb
	 * @mbggenerated
	 */
	private Integer wxjcb;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.user_img
	 * @mbggenerated
	 */
	@Length(message = "{m2b.userexpand.userImg.validation.length}", max = 255)
	private String userImg;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.create_time
	 * @mbggenerated
	 */
	@NotEmpty(message = "{m2b.userexpand.createTime.validation.notempty}")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.user_id
	 * @return  the value of b2b_user_expand.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.user_id
	 * @param userId  the value for b2b_user_expand.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.company
	 * @return  the value of b2b_user_expand.company
	 * @mbggenerated
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.company
	 * @param company  the value for b2b_user_expand.company
	 * @mbggenerated
	 */
	public void setCompany(String company) {
		this.company = company == null ? null : company.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.birthday
	 * @return  the value of b2b_user_expand.birthday
	 * @mbggenerated
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.birthday
	 * @param birthday  the value for b2b_user_expand.birthday
	 * @mbggenerated
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.job
	 * @return  the value of b2b_user_expand.job
	 * @mbggenerated
	 */
	public String getJob() {
		return job;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.job
	 * @param job  the value for b2b_user_expand.job
	 * @mbggenerated
	 */
	public void setJob(String job) {
		this.job = job == null ? null : job.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.qqjcb
	 * @return  the value of b2b_user_expand.qqjcb
	 * @mbggenerated
	 */
	public Integer getQqjcb() {
		return qqjcb;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.qqjcb
	 * @param qqjcb  the value for b2b_user_expand.qqjcb
	 * @mbggenerated
	 */
	public void setQqjcb(Integer qqjcb) {
		this.qqjcb = qqjcb;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.wxjcb
	 * @return  the value of b2b_user_expand.wxjcb
	 * @mbggenerated
	 */
	public Integer getWxjcb() {
		return wxjcb;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.wxjcb
	 * @param wxjcb  the value for b2b_user_expand.wxjcb
	 * @mbggenerated
	 */
	public void setWxjcb(Integer wxjcb) {
		this.wxjcb = wxjcb;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.user_img
	 * @return  the value of b2b_user_expand.user_img
	 * @mbggenerated
	 */
	public String getUserImg() {
		return userImg;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.user_img
	 * @param userImg  the value for b2b_user_expand.user_img
	 * @mbggenerated
	 */
	public void setUserImg(String userImg) {
		this.userImg = userImg == null ? null : userImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.create_time
	 * @return  the value of b2b_user_expand.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. copyright @ www.9he.com b2b_user_expand.create_time
	 * @param createTime  the value for b2b_user_expand.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}