package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class userBalance implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.user_id
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.userbalance.userId.validation.notempty}")
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.money
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.userbalance.money.validation.notempty}")
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_sj
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.userbalance.chargeSj.validation.notempty}")
    private Date chargeSj;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_type
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.userbalance.chargeType.validation.notempty}")
    private Integer chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_order
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.userbalance.chargeOrder.validation.notempty}")
    @Length(message = "{m2b.userbalance.chargeOrder.validation.length}", max = 30)
    private String chargeOrder;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_log
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.userbalance.chargeLog.validation.notempty}")
    @Length(message = "{m2b.userbalance.chargeLog.validation.length}", max = 100)
    private String chargeLog;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.id
     *
     * @return the value of mall_user_balance.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.id
     *
     * @param id the value for mall_user_balance.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.user_id
     *
     * @return the value of mall_user_balance.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.user_id
     *
     * @param userId the value for mall_user_balance.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.money
     *
     * @return the value of mall_user_balance.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.money
     *
     * @param money the value for mall_user_balance.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_sj
     * @param chargeSj 
     *
     * @return the value of mall_user_balance.charge_sj
     *
     * @mbggenerated
     */
    public Date getChargeSj() {
        return chargeSj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_sj
     *
     * @param chargeSj the value for mall_user_balance.charge_sj
     *
     * @mbggenerated
     */
    public void setChargeSj(Date chargeSj) {
        this.chargeSj = chargeSj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_type
     *
     * @return the value of mall_user_balance.charge_type
     *
     * @mbggenerated
     */
    public Integer getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_type
     *
     * @param chargeType the value for mall_user_balance.charge_type
     *
     * @mbggenerated
     */
    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_order
     *
     * @return the value of mall_user_balance.charge_order
     *
     * @mbggenerated
     */
    public String getChargeOrder() {
        return chargeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_order
     *
     * @param chargeOrder the value for mall_user_balance.charge_order
     *
     * @mbggenerated
     */
    public void setChargeOrder(String chargeOrder) {
        this.chargeOrder = chargeOrder == null ? null : chargeOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_log
     *
     * @return the value of mall_user_balance.charge_log
     *
     * @mbggenerated
     */
    public String getChargeLog() {
        return chargeLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com mall_user_balance.charge_log
     *
     * @param chargeLog the value for mall_user_balance.charge_log
     *
     * @mbggenerated
     */
    public void setChargeLog(String chargeLog) {
        this.chargeLog = chargeLog == null ? null : chargeLog.trim();
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("userBalance [id=");
		builder.append(id);
		builder.append(", userId=");
		builder.append(userId);
		builder.append(", money=");
		builder.append(money);
		builder.append(", chargeSj=");
		builder.append(chargeSj);
		builder.append(", chargeType=");
		builder.append(chargeType);
		builder.append(", chargeOrder=");
		builder.append(chargeOrder);
		builder.append(", chargeLog=");
		builder.append(chargeLog);
		builder.append("]");
		return builder.toString();
	}
    
    
}