package com.i9he.m2b.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class Wallet implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.user_id
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.wallet.userId.validation.notempty}")
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.password
     *
     * @mbggenerated
     */
    @NotEmpty(message = "{m2b.wallet.password.validation.notempty}")
    @Length(message = "{m2b.wallet.password.validation.length}", max = 50)
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.create_time
     *
     * @mbggenerated
     */
    private Date createTime;
    
    private Integer errorAll;

    /**
     * This field was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet
     *
     * @mbggenerated
     * 
     * 
     */
    
    private Integer errorCount;
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.id
     *
     * @return the value of b2b_user_wallet.id
     *
     * @mbggenerated
     */
    
    
    
    public Integer getId() {
        return id;
    }

    
	public Integer getErrorAll() {
		return errorAll;
	}


	public void setErrorAll(Integer errorAll) {
		this.errorAll = errorAll;
	}


	public Integer getErrorCount() {
		return errorCount;
	}

	public void setErrorCount(Integer errorCount) {
		this.errorCount = errorCount;
	}


	/**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.id
     *
     * @param id the value for b2b_user_wallet.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.user_id
     *
     * @return the value of b2b_user_wallet.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.user_id
     *
     * @param userId the value for b2b_user_wallet.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.password
     *
     * @return the value of b2b_user_wallet.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.password
     *
     * @param password the value for b2b_user_wallet.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.money
     *
     * @return the value of b2b_user_wallet.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.money
     *
     * @param money the value for b2b_user_wallet.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.create_time
     *
     * @return the value of b2b_user_wallet.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * copyright @ www.9he.com b2b_user_wallet.create_time
     *
     * @param createTime the value for b2b_user_wallet.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}